In [1]:
from ipywidgets import Textarea
import compe

In [2]:
open = compe.custom_open()
input = compe.custom_input()

text_area = Textarea()
text_area.observe(open.updater, names='value')
display(text_area)

Textarea(value='')

In [104]:
n, K = map(int, input().split())
a = sorted(list(map(int, input().split())))
inf = 10**18 + 1
l = -1 * inf
r = inf
while(l + 1 < r):
  c = (l + r)//2
  count = 0
  for i in range(n):
    #a[i]の符号で場合分け
    #a[i] < 0 の場合あるkが存在してk < jならばa[i]*a[j]はある値x未満になる。 
    if a[i] < 0:
      start = -1 #OUT
      end = n #OK
      while start + 1 < end:
        mid = (start + end) //2
        if a[i] * a[mid] < c:
          end = mid
        else:
          start = mid
      count += (n-end)
      if start < i:
        count -= 1
    
    else:#a[i]の符号が逆なので前と逆の操作を行えばよい。
      start = -1 #OK
      end = n #OUT
      while start + 1 < end:
        mid = (start + end)//2
        if a[i] * a[mid] < c:
          start = mid
        else:
          end = mid
      count += end

      if a[i] * a[i] < c:
        count -= 1
  count = (count // 2)
  print(l,c,count,r)  
  if count < K:
    l = c
  else:
    r = c
print(l)

-1000000000000000001 0 4110276950 1000000000000000001
0 500000000000000000 9508176172 1000000000000000001
0 250000000000000000 8476962056 500000000000000000
0 125000000000000000 7607289385 250000000000000000
0 62500000000000000 6993576687 125000000000000000
62500000000000000 93750000000000000 7322285699 125000000000000000
62500000000000000 78125000000000000 7164613829 93750000000000000
78125000000000000 85937500000000000 7245000278 93750000000000000
85937500000000000 89843750000000000 7284016040 93750000000000000
85937500000000000 87890625000000000 7264608218 89843750000000000
87890625000000000 88867187500000000 7274331241 89843750000000000
88867187500000000 89355468750000000 7279182146 89843750000000000
88867187500000000 89111328125000000 7276758061 89355468750000000
89111328125000000 89233398437500000 7277970699 89355468750000000
89233398437500000 89294433593750000 7278576957 89355468750000000
89233398437500000 89263916015625000 7278273685 89294433593750000
89233398437500000 89248657

In [79]:
import numpy as np
N,K=map(int,input().split())
A=list(map(int,input().split()))

A=np.array(A)

A_pos=np.sort(A[A>0])
A_neg=np.sort(A[A<0])
A_neg2=-A_neg[::-1]
n_pos=len(A_pos)
n_neg=len(A_neg)
n_zero=N-n_pos-n_neg

def position_in_neg(x):
    y=n_pos-np.searchsorted(A_pos,x//A_neg,side='right')
    return y.sum()

def position_in_pos(x):
    z=np.searchsorted(A_pos,-(-x//A_pos),side='left')
    w=np.searchsorted(A_neg2,-(-x//A_neg2),side='left')
    tmp=len(A_pos[A_pos**2<x])+len(A_neg2[A_neg2**2<x])
    return (z.sum()+w.sum()-tmp)//2

def position(x):
    if x<0:
        return position_in_neg(x)
    elif x==0:
        return n_pos*n_neg
    else:
        return position_in_pos(x)+n_pos*n_neg+(n_pos+n_neg)*n_zero+n_zero*(n_zero-1)//2

l=-pow(10,18)
r=pow(10,18)
while(r-l>1):
    mid=(l+r)//2
    if position(mid)<K:
        l=mid
    else:
        r=mid
print(l)

0


In [68]:
position(0)

1330494732

In [86]:
x=-300000000000000000

In [87]:
x//A_neg

array([      300000282,       300001338,       300003205, ...,
         3528789037228,  23758612497030, 307692307692307])

In [88]:
np.searchsorted(A_pos,x//A_neg,side='right')

array([11040, 11040, 11040, ..., 36538, 36538, 36538])

In [91]:
x=300000000000

In [94]:
-(-x//A_pos)

array([6825318, 5883738, 2993266, ...,     301,     301,     301])

In [92]:
np.searchsorted(A_pos,-(-x//A_pos),side='left')

array([273, 235, 111, ...,   0,   0,   0])

In [1]:
import numpy as np

def position_in_neg(x):
    y=n_pos-np.searchsorted(A_pos,x//A_neg,side='right')
    return y.sum()

def position_in_pos(x):
    z=np.searchsorted(A_pos,-(-x//A_pos),side='left')
    w=np.searchsorted(A_neg2,-(-x//A_neg2),side='left')
    tmp=len(A_pos[A_pos**2<x])+len(A_neg2[A_neg2**2<x])
    return (z.sum()+w.sum()-tmp)//2

def position(x):
    if x<0:
        return position_in_neg(x)
    elif x==0:
        return n_pos*n_neg
    else:
        return position_in_pos(x)+n_pos*n_neg+(n_pos+n_neg)*n_zero+n_zero*(n_zero-1)//2


def resolve():
    print("yes")
    N,K=map(int,input().split())
    A=list(map(int,input().split()))

    A=np.array(A)
    global A_pos,A_neg,A_neg2,n_pos,n_neg,n_zero
    A_pos=np.sort(A[A>0])
    A_neg=np.sort(A[A<0])
    A_neg2=-A_neg[::-1]
    n_pos=len(A_pos)
    n_neg=len(A_neg)
    n_zero=N-n_pos-n_neg


    l=-pow(10,18)
    r=pow(10,18)
    while(r-l>1):
        mid=(l+r)//2
        if position(mid)<K:
            l=mid
        else:
            r=mid
    
    print(l)


In [4]:
import sys
from io import StringIO
import unittest

class TestClass(unittest.TestCase):
    def assertIO(self, input, output):
        stdout, stdin = sys.stdout, sys.stdin
        sys.stdout, sys.stdin = StringIO(), StringIO(input)
        resolve()
        sys.stdout.seek(0)
        out = sys.stdout.read()[:-1]
        sys.stdout, sys.stdin = stdout, stdin
        self.assertEqual(out, output)
    def test_入力例_1(self):
        input = """4 3
3 3 -4 -2"""
        output = """-6"""
        self.assertIO(input, output)
    def test_入力例_2(self):
        input = """10 40
5 4 3 2 -1 0 0 0 0 0"""
        output = """6"""
        self.assertIO(input, output)
    def test_入力例_3(self):
        input = """30 413
-170202098 -268409015 537203564 983211703 21608710 -443999067 -937727165 -97596546 -372334013 398994917 -972141167 798607104 -949068442 -959948616 37909651 0 886627544 -20098238 0 -948955241 0 -214720580 277222296 -18897162 834475626 0 -425610555 110117526 663621752 0"""
        output = """448283280358331064"""
        self.assertIO(input, output)

if __name__ == "__main__":
    unittest.main(argv=['first-arg-is-ignored'], exit=False)

KeyboardInterrupt: 

In [20]:
unittest.main(argv=['first-arg-is-ignored'], exit=False)

KeyboardInterrupt: 

In [1]:
from ABC155_D import *



import sys
from io import StringIO
import unittest
class TestClass(unittest.TestCase):
    
    def assertIO(self, input, output):
        stdout, stdin = sys.stdout, sys.stdin
        sys.stdout, sys.stdin = StringIO(), StringIO(input)
        resolve()
        sys.stdout.seek(0)
        out = sys.stdout.read()[:-1]
        sys.stdout, sys.stdin = stdout, stdin
        self.assertEqual(out, output)
        
    def test_入力例_1(self):
        input = """4 3
3 3 -4 -2"""
        output = """-6"""
        self.assertIO(input, output)
        
#     def test_入力例_2(self):
#         input = """10 40
# 5 4 3 2 -1 0 0 0 0 0"""
#         output = """6"""
#         self.assertIO(input, output)
        
#     def test_入力例_3(self):
#         input = """30 413
# -170202098 -268409015 537203564 983211703 21608710 -443999067 -937727165 -97596546 -372334013 398994917 -972141167 798607104 -949068442 -959948616 37909651 0 886627544 -20098238 0 -948955241 0 -214720580 277222296 -18897162 834475626 0 -425610555 110117526 663621752 0"""
#         output = """448283280358331064"""
#         self.assertIO(input, output)


   

In [21]:
unittest.main(exit=False)

IndexError: list index out of range

In [2]:
sys.argv

['/Users/masaya/.pyenv/versions/3.7.5/lib/python3.7/site-packages/ipykernel_launcher.py',
 '-f',
 '/Users/masaya/Library/Jupyter/runtime/kernel-efba5f48-338f-4a20-89b4-33200b68a7ca.json']

In [18]:
del sys.argv[0]

In [1]:
def add(a, b):
    return a + b

In [3]:

import unittest

class TestNotebook(unittest.TestCase):

    def test_add(self):
        self.assertEqual(add(2, 2), 4)
        
    def test_add1(self):
        self.assertNotEqual(add(2, 2), 5)

    def test_add2(self):
        self.assertEqual(add(2, 3), 5)



In [4]:
if __name__ == "__main__":
    unittest.main(argv=['ignored', '-v'], verbosity=2, exit=False)

test_add (__main__.TestNotebook) ... ok
test_add1 (__main__.TestNotebook) ... ok
test_add2 (__main__.TestNotebook) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.003s

OK


In [5]:
unittest.main(argv=['ignored', '-v'], verbosity=2, exit=False)

test_add (__main__.TestNotebook) ... ok
test_add1 (__main__.TestNotebook) ... ok
test_add2 (__main__.TestNotebook) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.002s

OK
