# テストケースの標準入力を簡単にする方法
https://qiita.com/noca/items/00646efd9d4a7302f522

In [8]:
from ipywidgets import Textarea
import io

if 'open' in globals():
    del open
if 'input' in globals():
    del input

original_open = open

class custom_open():
    def __init__(self):
        self.text = ''

    def __call__(self, file, *args, **kwargs):
        if file == 0:
            return io.StringIO(self.text)
        return original_open(file, *args, **kwargs)

    def updater(self, change):
        self.text = change["new"]

class custom_input():
    def __init__(self):
        self.__sio = io.StringIO('')
        self.shell = get_ipython()
        if self.shell.events.callbacks['pre_run_cell'] != []:
            self.shell.events.callbacks['pre_run_cell'] = []
        self.shell.events.register('pre_run_cell', self.pre_run_cell)

    def __call__(self):
        return self.__sio.readline().strip()

    def pre_run_cell(self, info):
        text = self.shell.user_ns.get('text_area', None).value
        self.__sio = io.StringIO(text)

open = custom_open()
input = custom_input()

text_area = Textarea()
text_area.observe(open.updater, names='value')
display(text_area)

Textarea(value='')

## 使い方
上のボックスに入力例を代入するだけ
inputとopenが再定義されるので例えばもとのopenに戻したいときは
```
del open
```
を実行する

In [27]:
for s in open(0):
    print(s)

10 10 3

1 5

3 6

7 10

5 8

4 4

1 4

2 9

1 3

1 1

4 5

1 6

2 7

10 1


In [29]:
open(0)

In [30]:
D = open(0).read()

In [31]:
D

'10 10 3\n1 5\n3 6\n7 10\n5 8\n4 4\n1 4\n2 9\n1 3\n1 1\n4 5\n1 6\n2 7\n10 1'

In [32]:
print(D)

10 10 3
1 5
3 6
7 10
5 8
4 4
1 4
2 9
1 3
1 1
4 5
1 6
2 7
10 1


In [26]:
type(D[0][0])

str

In [13]:
(W, H, N), *D, = [list(map(int, s.split())) for s in open(0)]

In [14]:
print(W,H,N)

10 10 3


In [15]:
print(D)

[[1, 5], [3, 6], [7, 10], [5, 8], [4, 4], [1, 4], [2, 9], [1, 3], [1, 1], [4, 5], [1, 6], [2, 7], [10, 1]]


In [16]:
type(D[0][0])

int

# 二分探索

In [1]:
def binary_search(array,element):
    #array must be sorted
    n=len(array)
    l=0
    r=n
    while(r-l>=1):
        i=(l+r)//2
#         print(array[i],l,i,r)
        if element == array[i]:
            return True
           
        elif element > array[i]:
            l=i+1
        else:
            r=i
        
    
#         if jf==ji:
#             break
#     print(l,i,r)
    return False    

## example

In [8]:
a=[1,2,3,4,5,7,8,9,10]

In [10]:
# array must be sorted
binary_search(a,6)

False

## 二分探索その２

In [26]:
n=5
a=[1,1,1,1,1,2,3,3,5,6]
k=2

In [27]:

#array must be sorted
n=len(a)
lb=-1
ub=n
while(ub-lb>1):
    mid=(lb+ub)//2
    if a[mid]>=k:
        ub=mid
    else:
        lb=mid




In [28]:
a[ub]

2

# 浮動小数点数

In [5]:
import math
def my_round(x, d=0):
    p = 10 ** d
    return float(math.floor((x * p) + math.copysign(0.5, x)))/p

## example
- pythonは桁の丸め方が変(roundは四捨五入の関数)

In [12]:
round(1.5)

2

In [11]:
round(2.5)

2

In [7]:
my_round(0.44444,2)

0.44

In [9]:
0.3-0.1==0.2

False

In [16]:
print(format(0.1, '.20f'))

0.10000000000000000555


In [17]:
print(format(0.2, '.20f'))

0.20000000000000001110


In [18]:
print(format(0.3, '.20f'))

0.29999999999999998890


# 深さ優先探索

In [3]:
def dfs(x,y):

    field[x][y]='.'

    
    for dx in [-1,0,1]:
        for dy in [-1,0,1]:
            nx=x+dx
            ny=y+dy
            
            if 0<=nx and nx<N and 0 <=ny and ny <M and field[nx][ny]=='W':
                dfs(nx,ny)
    return
    

## example

In [1]:
N=10
M=12

In [2]:
field=[['W','.','.','.','.','.','.','.','.','W','W','.'],
       ['.','W','W','W','.','.','.','.','.','W','W','W'],
       ['.','.','.','.','W','W','.','.','.','W','W','.'],
       ['.','.','.','.','.','.','.','.','.','W','W','.'],
       ['.','.','.','.','.','.','.','.','.','W','.','.'],
       ['.','.','W','.','.','.','.','.','.','W','W','.'],
       ['.','W','.','W','.','.','.','.','.','.','W','.'],
       ['W','.','W','.','W','.','.','.','.','.','W','.'],
       ['.','W','.','W','.','.','.','.','.','.','W','.'],
       ['.','.','W','.','.','.','.','.','.','.','W','.'],
      ]

In [4]:
import copy
see=[]
field2=copy.deepcopy(field)
see.append(field2)
res=0
for i in range(N):
    for j in range(M):

        if field[i][j]=='W':
            dfs(i,j)
            field2=copy.deepcopy(field)
            see.append(field2)
            
            res+=1
print(res)

3


# 幅優先探索

In [11]:
dx=[1,0,-1,0]
dy=[0,1,0,-1]
def bfs():
    que=[]
    for i in range(N):
        for j in range(M):
            d[i][j]=INF
#     print(d)       
    que.append([sx,sy])
    d[sx][sy]=0
#     print(d)  
    while(len(que)>0):
        p=que.pop(0)
        if p[0]==gx and p[1]==gy:
            break
        for i in range(4):
            nx=p[0]+dx[i]
            ny=p[1]+dy[i]
#             print(nx,ny, maze[nx][ny], d[nx][ny] )
            if 0<=nx and nx<N and 0<=ny and ny<M and maze[nx][ny] != '#' and d[nx][ny]==INF:

                que.append([nx,ny])
                d[nx][ny]=d[p[0]][p[1]]+1

    return d[gx][gy]

## example

In [22]:
INF=99
N=10
M=10
sx=0
sy=1
gx=9
gy=8
d=[[0 for j in range(M)] for i in range(N)]

In [27]:
maze = [['#','S','#','#','#','#','#','#','.','#'],
        ['.','.','.','.','.','.','#','.','.','#'],
        ['.','#','.','#','#','.','#','#','.','#'],
        ['.','#','.','.','.','.','.','.','.','.'],
        ['#','#','.','#','#','.','#','#','#','#'],
        ['.','.','.','.','#','.','.','.','.','.'],
        ['.','#','#','#','#','#','#','#','.','#'],
        ['.','.','.','.','#','.','.','.','.','.'],
        ['.','#','#','#','#','.','#','#','#','.'],
        ['.','.','.','.','#','.','.','.','G','#'],
        ]

In [28]:
res=bfs()

In [29]:
res

22

In [30]:
d

[[99, 0, 99, 99, 99, 99, 99, 99, 13, 99],
 [2, 1, 2, 3, 4, 5, 99, 13, 12, 99],
 [3, 99, 3, 99, 99, 6, 99, 99, 11, 99],
 [4, 99, 4, 5, 6, 7, 8, 9, 10, 11],
 [99, 99, 5, 99, 99, 8, 99, 99, 99, 99],
 [8, 7, 6, 7, 99, 9, 10, 11, 12, 13],
 [9, 99, 99, 99, 99, 99, 99, 99, 13, 99],
 [10, 11, 12, 13, 99, 17, 16, 15, 14, 15],
 [11, 99, 99, 99, 99, 18, 99, 99, 99, 16],
 [12, 13, 14, 15, 99, 19, 20, 21, 22, 99]]

# ベルマンフォード法

In [1]:

def shortest_path(s):
    INF = 1<<60
    d=[INF]*(V+1)
    d[s]=0
    update=0
    while(update==0):
        update=1
#         print(d)
        for i in range(len(edge)):
            e=edge[i]
#             print(e)
            if d[e[0]]!=INF and d[e[1]]>d[e[0]]+1:
                d[e[1]]=d[e[0]]+1
                update=0
    return d

In [2]:
V=9
edge=[[1, 2], [1, 3], [4, 2], [4, 3], [4, 5], [4, 6], [7, 5], [7, 6], [8, 9]]
ans=[]
for e in edge:
    ans.append([e[1],e[0]])
edge+=ans
edge.sort()

In [3]:
shortest_path(1)

[1152921504606846976,
 0,
 1,
 1,
 2,
 3,
 3,
 4,
 1152921504606846976,
 1152921504606846976]

# 動的計画法

In [1]:
n=4
w=[2,1,3,2] #重さ
v=[3,2,4,2] #値段
W=5 #最大容量

## 再帰関数を使った実装

In [4]:
def rec(i,j):
    
    if dp[i][j]>=0:
        return dp[i][j] 
    if i==n:
        res=0
    elif j<w[i]:
        res=rec(i+1,j)
    else:
        res=max(rec(i+1,j),rec(i+1,j-w[i])+v[i])
    
    dp[i][j]=res
    return dp[i][j]

In [5]:
dp=[[-1]*(W+1) for i in range(n+1)]
rec(0,W)

7

In [6]:
dp

[[-1, -1, -1, -1, -1, 7],
 [-1, -1, -1, 4, -1, 6],
 [-1, -1, 0, 4, 4, 4],
 [0, 0, 0, 0, 2, 2],
 [0, 0, 0, 0, 0, 0]]

## for文＋漸化式での実装

In [7]:
dp=[[0]*(W+1) for _ in range(n+1)]
for i in reversed(range(0,n)):
    for j in range(W+1):
        if j<w[i]:
            dp[i][j]=dp[i+1][j]
        else:
            dp[i][j]=max(dp[i+1][j], dp[i+1][j-w[i]]+v[i])

In [8]:
dp

[[0, 2, 3, 5, 6, 7],
 [0, 2, 2, 4, 6, 6],
 [0, 0, 0, 4, 4, 4],
 [0, 0, 0, 0, 2, 2],
 [0, 0, 0, 0, 0, 0]]

### 番号も記録

In [51]:
dp=[[[0,[]] for _ in range(W+1)] for _ in range(n+1)]
for i in reversed(range(0,n)):
    for j in range(W+1):
        if j<w[i]:
            dp[i][j][0]=dp[i+1][j][0]
        else:
            if dp[i+1][j][0] < dp[i+1][j-w[i]][0]+v[i]:
                dp[i][j][0]=dp[i+1][j-w[i]][0]+v[i]
                dp[i][j][1]=dp[i+1][j][1].copy()
                dp[i][j][1].append(i)
            else: 
                dp[i][j][0]=dp[i+1][j][0]
                dp[i][j][1]=dp[i+1][j][1].copy()

In [52]:
dp

[[[0, []], [2, []], [3, [0]], [5, [3, 2, 0]], [6, [3, 2, 1]], [7, [3, 2, 0]]],
 [[0, []], [2, [1]], [2, []], [4, [3, 2]], [6, [3, 2, 1]], [6, [3, 2]]],
 [[0, []], [0, []], [2, []], [4, [3, 2]], [4, [3, 2]], [6, [3, 2]]],
 [[0, []], [0, []], [2, [3]], [2, [3]], [2, [3]], [2, [3]]],
 [[0, []], [0, []], [0, []], [0, []], [0, []], [0, []]]]

- メモを分離

In [5]:
dp=[[0 for _ in range(W+1)] for _ in range(n+1)]
pick=[[[] for _ in range(W+1)] for _ in range(n+1)]

for i in reversed(range(0,n)):
    for j in range(W+1):
        if j<w[i]:
            dp[i][j]=dp[i+1][j]
            pick[i][j]=pick[i+1][j].copy()
        else:
            if dp[i+1][j] < dp[i+1][j-w[i]]+v[i]:
                dp[i][j]=dp[i+1][j-w[i]]+v[i]
                pick[i][j]=pick[i+1][j-w[i]].copy()
                pick[i][j].append(i)
            else: 
                dp[i][j]=dp[i+1][j]
                pick[i][j]=pick[i+1][j].copy()

In [6]:
dp

[[0, 2, 3, 5, 6, 7],
 [0, 2, 2, 4, 6, 6],
 [0, 0, 2, 4, 4, 6],
 [0, 0, 2, 2, 2, 2],
 [0, 0, 0, 0, 0, 0]]

In [7]:
pick

[[[], [1], [0], [1, 0], [2, 1], [2, 0]],
 [[], [1], [3], [2], [2, 1], [3, 2]],
 [[], [], [3], [2], [2], [3, 2]],
 [[], [], [3], [3], [3], [3]],
 [[], [], [], [], [], []]]

## 逆順での実装

In [23]:
dp=[[0]*(W+1) for _ in range(n+1)]
for i in range(n):
    for j in range(W+1):
        if j<w[i]:
            dp[i+1][j]=dp[i][j]
        else:
            dp[i+1][j]=max(dp[i][j],dp[i][j-w[i]]+v[i])

In [24]:
dp

[[0, 0, 0, 0, 0, 0],
 [0, 0, 3, 3, 3, 3],
 [0, 2, 3, 5, 5, 5],
 [0, 2, 3, 5, 6, 7],
 [0, 2, 3, 5, 6, 7]]

## その他

In [27]:
dp=[[0]*(W+1) for _ in range(n+1)]
for i in range(n):
    for j in range(W+1):
        dp[i+1][j]=max(dp[i+1][j],dp[i][j])
        if j+w[i]<=W:
            dp[i+1][j+w[i]]=max(dp[i+1][j+w[i]],dp[i][j]+v[i])



In [28]:
dp

[[0, 0, 0, 0, 0, 0],
 [0, 0, 3, 3, 3, 3],
 [0, 2, 3, 5, 5, 5],
 [0, 2, 3, 5, 6, 7],
 [0, 2, 3, 5, 6, 7]]

## Longest common subsequence

In [1]:
import numpy as np

In [2]:
n=4
m=4
s="abcxxde"
n=len(s)
t="ybyeycydyye"
m=len(t)

In [3]:
dp=np.zeros((n+1,m+1),int)
for i in range(n):
    for j in range(m):
        #print(i,j, s[i],t[j])
        if s[i]==t[j]:
            dp[i+1][j+1]=max(dp[i][j]+1,dp[i][j+1],dp[i+1][j])
        else:
            dp[i+1][j+1]=max(dp[i][j+1],dp[i+1][j])
print(dp[n][m])

4


In [15]:
dp

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
       [0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
       [0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
       [0, 0, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3],
       [0, 0, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4]])

# 個数制限なしナップサック問題

In [33]:
n=3
w=[3,4,2] #重さ
v=[4,5,3] #値段
W=7 #最大容量

In [36]:
dp=[[0]*(W+1) for _ in range(n+1)]
for i in range(n):
    for j in range(W+1):
        if j <w[i]:
            dp[i+1][j]=dp[i][j]
        else:
            dp[i+1][j]=max(dp[i][j],dp[i+1][j-w[i]]+v[i])

In [37]:
dp

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 4, 4, 4, 8, 8],
 [0, 0, 0, 4, 5, 5, 8, 9],
 [0, 0, 3, 4, 6, 7, 9, 10]]

## 配列を更新

In [45]:
n=4
w=[2,1,3,2] #重さ
v=[3,2,4,2] #値段
W=5 #最大容量

In [53]:
dp=[0]*(W+1)
for i in range(n):
    for j in range(W,w[i]-1,-1):
#         print(j)
#         print(j,dp[j])
        dp[j]=max(dp[j],dp[j-w[i]]+v[i])

In [54]:
dp

[0, 2, 3, 5, 6, 7]

In [ ]:
n=3
w=[3,4,2] #重さ
v=[4,5,3] #値段
W=7 #最大容量

In [55]:
dp=[0]*(W+1)
for i in range(n):
    for j in range(W+1):
        if j <w[i]:
            dp[j]=dp[j]
        else:
            dp[j]=max(dp[j],dp[j-w[i]]+v[i])

In [56]:
dp

[0, 2, 4, 6, 8, 10]

##  偶奇分け

In [63]:
dp=np.zeros((2,W+1),int)
for i in range(n):
    for j in range(W+1):
        
        if j <w[i]:
            dp[(i+1)&1][j]= dp[i&1][j]
        else:
            dp[(i+1)&1][j]= max(dp[i&1][j], dp[(i+1)&1][j-w[i]]+v[i])
#         print(dp)
#         print("")

In [60]:
dp

array([[ 0,  2,  4,  6,  8, 10],
       [ 0,  2,  4,  6,  8, 10]])

## Wが大きい時

In [96]:
n=4
w=[200,100,300,200] #重さ
v=[3,2,4,2] #値段
W=500 #最大容量

In [99]:
dp=np.zeros((n+1, n*max(v)+1),int)
dp[0][1:]= 1<<10
for i in range(n):
    for j in range(n*max(v)+1):
        if j <v[i]:
            dp[i+1][j]=dp[i][j]
        else:
            dp[i+1][j]=min(dp[i][j],dp[i][j-v[i]]+w[i])
res=0
for j in range(n*max(v)+1):
    if dp[n][j] <= W:
        res=j
print(res)

7


In [98]:
dp

array([[   0, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024,
        1024, 1024, 1024, 1024, 1024, 1024],
       [   0, 1024, 1024,  200, 1024, 1024, 1024, 1024, 1024, 1024, 1024,
        1024, 1024, 1024, 1024, 1024, 1024],
       [   0, 1024,  100,  200, 1024,  300, 1024, 1024, 1024, 1024, 1024,
        1024, 1024, 1024, 1024, 1024, 1024],
       [   0, 1024,  100,  200,  300,  300,  400,  500, 1024,  600, 1024,
        1024, 1024, 1024, 1024, 1024, 1024],
       [   0, 1024,  100,  200,  300,  300,  400,  500,  600,  600, 1024,
         800, 1024, 1024, 1024, 1024, 1024]])

## 個数制限付き部分和問題

In [106]:
n=3
a=[3,5,8]
m=[3,2,2]
K=17

## うまくないアルゴリズム

In [134]:
dp=np.full((n+1,K+1),False)
dp[0][0]=True
for i in range(n):
    for j in range(K+1):
        for k in range(m[i]+1):
            if k*a[i]<=j:
                dp[i+1][j]|=dp[i][j-k*a[i]]
if dp[n][K]:
    print("yes")
else:
    print("no")

yes


In [135]:
dp

array([[ True, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [ True, False, False,  True, False, False,  True, False, False,
         True, False, False, False, False, False, False, False, False],
       [ True, False, False,  True, False,  True,  True, False,  True,
         True,  True,  True, False,  True,  True, False,  True, False],
       [ True, False, False,  True, False,  True,  True, False,  True,
         True,  True,  True, False,  True,  True, False,  True,  True]])

## うまいコード

In [151]:
dp=np.full((K+1),-1)
dp[0]=0
for i in range(n):
    for j in range(K+1):
        if dp[j]>=0:
            dp[j]=m[i]
        elif (j<a[i]) or (dp[j-a[i]]<=0):
            dp[j]=-1
        else:
            dp[j]=dp[j-a[i]]-1

if dp[K]>=0:
    print("yes")
else:
    print("no")

yes


In [152]:
dp

array([ 2, -1, -1,  2, -1,  2,  2, -1,  2,  2,  2,  2, -1,  2,  2, -1,  2,
        1])

## Longest increasing subsequence

In [32]:
n=5
a=[4,2,3,1,5]

In [33]:
dp=[0]*(n+1)
res = 0
for i in range(n):
    dp[i]=1
    for j in range(i):
        if a[j]<a[i]:
            dp[i]=max(dp[i],dp[j]+1)
    res = max(res,dp[i])
print(res)

3


In [34]:
dp

[1, 1, 2, 1, 3, 0]

## partition

In [163]:
n=40
m=5
M=10000

In [164]:
dp=np.zeros((M+1,n+1),int)
dp[0][0]=1
for i in range(m+1):
    for j in range(n+1):
        if j>=i:
            dp[i][j]=dp[i-1][j]+dp[i][j-i]
        else:
            dp[i][j]=dp[i-1][j]

print(dp[m][n])

1747


## 重複組合せ

In [173]:
n=3
m=3
a=[1,2,3]
M=10000

In [178]:
dp=np.zeros((n+1,m+1),int)
for i in range(n+1):
    dp[i][0]=1
for i in range(n):
    for j in range(1,m+1):
        if j-1-a[1] >=0:
            dp[i+1][j]=dp[i+1][j-1]+dp[i][j]-dp[i][j-1-a[i]]
        else:
            dp[i+1][j]=dp[i+1][j-1]+dp[i][j]

In [179]:
dp[n][m]

6

In [180]:
dp

array([[1, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 2, 3, 3],
       [1, 3, 6, 6]])

## 最長共通部分列

In [ ]:
s="abcxxde"
n=len(s)
t="ybyeycydyye"
m=len(t)

In [75]:
def LCSsequence(s1,s2):
    n=len(s1)
    m=len(s2)
    dp=np.zeros((n+1,m+1),int)
    for i in range(n):
        for j in range(m):
            #print(i,j, s[i],t[j])
            if s1[i]==s2[j]:
                dp[i+1][j+1]=max(dp[i][j]+1,dp[i][j+1],dp[i+1][j])
            else:
                dp[i+1][j+1]=max(dp[i][j+1],dp[i+1][j])
    print(dp)
    return dp[n][m]
    

In [77]:
LCSsequence("aaabcdefg1", "baxxcxg0")

[[0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 1 1]
 [0 0 1 1 1 1 1 1 1]
 [0 0 1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1 1 1]
 [0 1 1 1 1 2 2 2 2]
 [0 1 1 1 1 2 2 2 2]
 [0 1 1 1 1 2 2 2 2]
 [0 1 1 1 1 2 2 2 2]
 [0 1 1 1 1 2 2 3 3]
 [0 1 1 1 1 2 2 3 3]]


3

In [89]:
# wrong code
def LCSsequence(s1, s2):
    l1, l2 = len(s1), len(s2)
    if l1 == 0 or l2 == 0: return ''

    # memorization of m[l1][l2]
    m = []
    for x in range(l1):
        m.append([0]*(l2))

    # Fill 0th row
    isSameFound = False
    for i in range(l1):
        if isSameFound or s1[i] == s2[0]:
            m[i][0] = 1
            isSameFound = True

    # Fill 0th column
    isSameFound = False
    for j in range(l2):
        if isSameFound or s2[j] == s1[0]:
            m[0][j] = 1
            isSameFound = True

    max_len = 0
    # m[i][j] stores the maximum length of subsequence of s1[:i+1], s2[:j+1]
    for i in range(0, l1-1):
        for j in range(0, l2-1):
            if s1[i+1] == s2[j+1]:
                m[i+1][j+1] = m[i][j] + 1
                max_len = max(m[i+1][j+1], max_len)
            else:
                m[i+1][j+1] = max(m[i][j+1], m[i+1][j])
                
    #If you want to know just the length of the lcs, return maxLen.
    #Here we'll try to print the lcs.
    lcs_str = ''
    i, j = l1-1, l2-1
    while i >= 0 and j >= 0:
        if s1[i] == s2[j]:
            lcs_str += s1[i] #or s2[j-1]
            i -= 1
            j -= 1
        else:
            if m[i-1][j] > m[i][j-1]:
                i -= 1
            else:
                j -= 1
    return lcs_str[::-1]

In [90]:
LCSsequence("zzzbaxxcxg","yyyabcdefg")

'acg'

解がuniqueにならない. 上の例ではacgとbcgの２種類解

In [92]:
LCSsequence("aaaaxxcxg","abcdefg")

'cg'

更に上のコードではacgが帰ってこない

## 最長共通部分文字列

In [27]:
def LCSstring(s1, s2):
    if not s1 or not s2:
        return 0

    len1, len2 = len(s1), len(s2)

    # memorization
    m = []
    for i in range(len1):
        m.append([0]*len2) #m[len1][len2]

    lcs = 0

    # set 1st index value
    for i, ch in enumerate(s1):
        if ch == s2[0]:
            m[i][0] = 1
            lcs = 1
    for i, ch in enumerate(s2):
        if ch == s1[0]:
            m[0][i] = 1
            lcs = 1

    # m[i][j] stands for s1[i] and s2[j]
    # is the m[i][j] th bit of a common substring
    i_position=0
    for i in range(1, len1):
        for j in range(1, len2):
            if s1[i] == s2[j]:
                m[i][j] = m[i-1][j-1] + 1
                if m[i][j] > lcs:
                    lcs=m[i][j]
                    i_position=i
            else:
                m[i][j] = 0
    
    #print(lcs,i_position)
    #return lcs
    #return m        
    return s1[i_position-lcs+1:i_position+1] 
     

In [28]:
LCSstring("abcdefg", "abxxxcxxg")

'ab'

# 巡回セールスマン問題

In [40]:
# S=既に訪れた頂点(２進数を使って表現している), v=現在の位置
INF = 1<<60
def rec(S,v):
    if dp[S][v]>=0:
        return dp[S][v]
    
    if S==(1<<N)-1 and v==0:
        dp[S][v]=0
        return dp[S][v]
    
    res=INF
    for u in range(N):
        if (S>>u & 1)!=1:
            res=min(res,rec(S|1<<u,u)+G[v][u])
    
    dp[S][v]=res
    return dp[S][v]

In [41]:
N=5
# G=[[0,3,0,4,0],
#    [0,0,5,0,0],
#    [4,0,0,5,0],
#    [0,0,0,0,3],
#    [7,6,0,0,0]]

G=[[INF,3,INF,4,INF],
   [INF,INF,5,INF,INF],
   [4,INF,INF,5,INF],
   [INF,INF,INF,INF,3],
   [7,6,INF,INF,INF]]

In [42]:
dp=[[-1]*N for _ in range((1<<5))]
rec(0,0)

22

# mod計算

In [1]:
mod=10 ** 9 + 7

# power

In [5]:
pow(2,n,mod)

140625001

## binomial

In [3]:
n=10**9
a=12345

In [2]:
def binomial(n,k):
    x=1
    y=1
    for i in range(k):
        x=x*(n-i)%mod
        y=y*(i+1)%mod
    return x*pow(y,mod-2,mod)%mod

In [4]:
binomial(n,a)

463571078

# しゃくとり法

In [6]:
n=10
S=15
a=[5,1,3,5,10,7,4,9,2,8]

In [7]:
res=n+1
s=0
t=0
summation=0
while(True):
    while(t<n and summation<S):
        summation+=a[t]
        t+=1
    if (summation<S):
        break
    print(s,t,summation)
    res=min(res,t-s)
    summation-=a[s]
    s+=1

0 5 24
1 5 19
2 5 18
3 5 15
4 6 17
5 8 20
6 9 15
7 10 19


In [8]:
res

2