In [1]:
from ipywidgets import Textarea
import compe

In [2]:
open = compe.custom_open()
input = compe.custom_input()

text_area = Textarea()
text_area.observe(open.updater, names='value')
display(text_area)


Textarea(value='')

In [84]:
A,B = map(str,input().split())
ans=int(A)*(100*int(B[0])+10*int(B[2])+int(B[3]))
print(ans//100)

1000000000


In [79]:
B[1]

'.'

In [61]:
math.floor(2.5)

2

In [31]:
import numpy as np
N=int(input())
A=list(map(int,input().split()))
A=np.array(A)
ans=np.prod(A)
if ans > 10**18:
    ans=-1
print(ans)

-1


In [29]:
N=int(input())
AB=[]
for _ in range(N):
    AB.append(list(map(int,input().split())))


In [34]:
count=0
for i in range(N-1):
    for j in range(i+1,N):
        if np.dot(AB[i],AB[j])==0:
            count+=1

In [37]:
2**N-1-count

6

In [4]:
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import dijkstra


N,M = map(int,input().split())
graph=np.zeros((N+1,N+1),int)
for _ in range(M):
    a,b=map(int,input().split())
    graph[a,b]=1
    graph[b,a]=1




graph = csr_matrix(graph)
dist_matrix, predecessors = dijkstra(csgraph=graph, directed=False, indices=1, return_predecessors=True)

if np.count_nonzero(dist_matrix[1:] >N)==0:
    ans=predecessors[2:]
    print("Yes")
    for a in ans:
        print(a)
else:
    print("No")

Yes
36176
15090
45433
22380
32228
12044
21184
4496
32341
50968
21006
40114
22486
55374
32229
51970
18612
34661
14516
18265
20673
16485
32090
32990
13610
9742
4361
25616
21492
11440
31517
49357
42656
296
41857
38896
42766
3246
41722
15116
34740
9205
20120
27852
34080
32375
55694
5843
15878
13320
42647
1029
44509
31796
6714
52147
50124
7496
42328
52538
34666
48233
17681
42260
27734
23103
22590
37952
55238
22531
5213
16399
2403
35363
50172
17588
16805
50951
54325
25049
16536
18539
21862
21533
53249
16186
7947
26354
42031
41000
2796
36141
19014
53936
28608
37383
24564
45813
29067
1654
52768
35647
6165
34162
37959
22908
15055
14037
3059
18280
35093
2954
6747
13524
4990
21144
14420
41018
8070
9144
40553
21209
36982
53779
19795
46191
18731
27331
51579
6400
379
47133
22037
33438
8620
13253
47822
21770
40871
40955
24280
48358
37225
15052
34734
54269
46949
17602
53875
12252
31058
17665
31623
52233
22679
45127
210
18633
51007
54616
14587
19448
22351
29981
25276
55526
4469
3911
7504
44829
31732
53

45978
24286
37454
23572
53067
16989
26701
3246
44565
10463
13604
34289
45485
32262
27097
19014
49042
20259
23142
11108
36352
36588
33276
14176
16339
5588
53413
18477
13745
19019
53472
50178
40320
31206
9189
27921
49556
47649
6163
30026
45065
4477
48483
45175
53930
34015
23700
48706
51922
25436
2760
34683
1798
23771
25033
27066
55810
31989
20153
36577
15597
55321
42711
51383
4548
37443
46993
10849
10867
42478
20328
23130
27330
31635
53010
34163
32428
22641
12464
40356
26855
15816
6030
47033
18053
46657
32185
27134
16016
14401
54378
55469
37929
43385
24211
14941
3801
2650
32438
45538
4906
50298
53143
44313
40327
29531
8285
11755
52721
30220
26591
16005
31374
5766
41204
1544
2854
31632
28587
50672
10943
21729
54092
25936
14727
54319
9076
8425
27215
17377
14480
26736
10507
4359
44443
11202
33573
33264
5246
33
25296
445
29710
43474
1505
27408
12199
27059
5876
9228
42301
23806
14446
1146
33391
12559
45731
55586
16826
43403
7994
45469
816
7116
54094
30746
10985
43032
11706
2877
50849
4580
207

9004
50030
4201
41775
18882
22675
42741
14277
2167
4210
13135
46811
28410
48424
7305
34427
40534
15144
43281
45572
35161
9192
25542
29426
874
45694
16496
48875
37018
43920
34798
637
13937
9552
29241
10555
14315
45422
39832
52849
26267
45612
51729
42532
26406
49102
45872
23016
48840
11308
11912
24432
6536
48176
27327
20348
42230
15656
20909
30338
17535
39908
33067
44537
39593
53015
53975
47668
807
30168
9036
38949
12763
18575
27724
36962
24535
20989
29216
51404
53824
9104
50321
26303
23337
6062
36849
39042
55282
30473
12717
46403
50181
4756
49259
33768
5594
39103
3826
48187
29784
31384
41846
52427
51927
34843
26247
43152
44503
52358
48283
4796
55621
1216
3844
10713
18723
15052
30326
39529
24202
18926
32565
47636
23034
30474
42586
40448
4992
56027
48402
36948
43512
33304
34093
21193
21414
15240
884
31024
45651
43426
2254
50255
53321
45223
29824
17418
45463
38101
32604
6952
27441
32362
33133
31775
3621
5121
42651
36859
1804
21860
9431
48683
45788
3
16018
44465
40396
49554
21728
6616
20489

11043
25930
34684
4016
26974
9013
46095
12850
4700
1039
31708
12059
53157
1185
50154
14149
52037
53540
35212
20092
15107
46948
26397
16184
19629
54964
44870
30446
41281
16410
51010
18521
2824
6589
50003
34298
54277
18200
53958
53284
731
52704
13010
9476
30039
1846
52179
3088
4873
7862
17019
9284
39013
51622
34754
53752
12536
23054
44280
41523
48755
8679
2587
13539
28099
22677
7042
15291
34012
27860
49931
9991
10306
25266
16901
1645
5144
47794
10068
3190
34185
44750
14342
33370
48323
5213
30854
4807
36362
22729
26273
25039
38044
16671
21244
40695
22953
35063
38928
30951
48736
26170
31635
28992
33887
21689
193
40632
15878
232
3626
39504
41186
53846
35901
44655
56147
16801
53873
45249
34255
44426
52903
48987
33669
28270
34499
21710
45498
48920
50109
33007
38393
48940
10545
13900
17469
17208
17502
34229
20435
724
42181
38280
42193
21709
28873
24588
26470
46782
17251
53118
31107
41765
47382
44333
11508
42410
29925
40560
16783
33150
40066
10585
55655
18802
18431
17488
19945
48633
26482
9325


25394
55544
42293
34947
20991
7081
11816
22209
6478
24792
17011
49998
35013
32995
26982
54446
41893
33920
15330
51068
47631
15964
52698
25330
2062
40529
40832
37038
33728
151
12998
28321
13162
22041
36885
8909
4167
53323
19337
6384
53726
32866
21479
38337
15551
7460
15593
36446
49259
54765
39840
48952
27838
4599
7593
48162
32483
28795
21973
10079
35949
31872
29879
38649
25984
21978
36351
52453
38748
46201
34541
5720
3274
6991
55286
33362
16147
13131
29618
31727
27961
2058
37389
52892
29403
16853
17797
19413
34871
36265
10611
41448
46505
22913
17427
24137
11079
2052
52804
33983
186
2401
51686
2713
8237
840
7979
8162
9659
27703
51029
47936
22317
10292
50025
47096
42157
49797
13365
53097
47274
30389
39831
572
23785
38783
17608
17314
40504
40600
46401
34219
39583
41727
6431
51127
5435
36294
5367
2838
47048
5707
24164
30820
12595
25898
37082
53083
15361
32055
40456
33662
26073
22746
52314
24368
49694
2363
10021
31156
13070
41061
38053
29545
30105
33607
5815
20339
19158
319
14920
48455
52042

10047
50992
50142
56090
10433
21243
21982
33731
48540
36345
12997
28341
11688
50121
39125
38615
8368
28064
32476
28391
9057
12124
26098
26693
9754
35347
55567
42259
8231
32589
46872
46042
53707
39551
45505
45002
44411
30925
41815
9671
43861
30418
43298
27411
26998
47685
8092
46317
6153
42233
21922
49186
5332
15351
21998
18117
28915
16017
12332
22247
51317
6913
54368
4045
55029
2177
15565
54317
5909
41531
1962
11237
18456
21847
45662
11090
15202
17576
21589
52934
51309
2779
49241
11189
41125
2262
12206
34700
7178
49985
43713
16906
13194
20902
42053
1152
51876
36023
14506
45238
40637
49552
26318
7629
4790
12724
13704
4310
23371
17697
30774
6608
567
45191
28243
51743
36990
3473
13038
43742
17078
55743
24637
43226
26334
41959
42735
2253
29685
4983
29064
16026
27164
27814
13093
30820
14722
48316
14181
10170
30820
12608
5017
22565
48284
38260
17614
19944
44030
14538
4602
33734
17130
44522
33773
8169
41754
24582
17301
11903
16474
42458
36586
33893
37069
6655
29680
26174
32155
10968
5619
21669

27656
17505
52679
44442
44659
23904
30996
24348
7656
3193
3342
25327
31002
7447
51536
29729
28661
12955
14396
32282
19719
54829
9626
40595
20517
7410
41481
50676
46118
34622
51218
34093
5492
37485
15643
48069
28027
6032
31169
27110
38453
15401
10055
52457
41649
20343
15693
25045
37056
18475
5856
886
33172
25571
25535
33301
49426
2390
3416
48546
3493
41313
14682
32666
10762
53630
14463
19247
53747
44340
48084
1780
6304
47659
55719
30575
18810
15067
5093
2174
6335
42126
2622
40200
19426
13638
14668
30552
26182
45806
21170
52050
19728
19102
41401
15540
37976
11559
41461
52099
16442
46600
17023
16846
11276
26245
31338
13185
11998
19250
51652
27357
5388
15894
39219
3776
48694
52711
33721
46803
19308
23354
38766
8921
26580
24415
53276
35862
1015
39589
19064
27691
11453
40854
20530
22269
12282
13779
1722
2145
1583
42073
24055
10131
44585
6696
50698
7760
36222
250
8615
2810
43667
40873
8937
30307
16686
36427
42841
43135
35474
39933
31692
28264
49538
35166
54944
50817
30716
17380
23742
36010
75

12686
34922
33244
54518
37455
39281
35912
47897
3820
30311
25122
10874
13797
53516
8462
33215
55441
42064
50315
4277
26489
16026
12106
37724
21435
5605
38969
4932
56026
20912
54392
10094
13042
47479
47502
9711
52043
35443
20402
43427
52317
50026
24968
54331
9705
20303
5915
10224
37645
10670
38302
48656
22831
9171
38222
8009
9440
41808
41299
14334
51068
13813
9855
2094
46278
38395
21728
16438
21507
9059
28329
32587
18339
20436
42688
34635
42524
52814
29369
9124
7926
39522
21272
47289
11387
12268
4800
30418
4417
735
28420
6292
32102
29786
27108
47695
17459
2400
496
6091
44611
18954
2055
1445
39570
14661
35622
14131
43492
51342
27739
46301
32130
27517
46907
55504
47167
23907
36474
36838
10099
5273
11391
47803
1677
12818
20680
18786
55777
33501
23707
49879
4843
43386
313
15969
26106
32446
17853
35350
3117
23173
33569
44506
41979
22123
49104
52350
25329
20900
42325
39870
614
12622
38433
55505
18526
10077
36855
31563
43387
46484
4365
15419
48856
14432
52455
50431
7209
7285
9819
13465
25930
4

16275
1125
27658
44389
28849
26597
47170
31982
19888
39268
28347
28291
34175
4599
43949
50279
46986
42798
50609
26198
22784
16632
18031
43042
12635
22367
14638
1183
54889
32870
42007
37118
43384
27085
39502
23116
51878
38127
33526
54572
27498
31341
40223
36160
11566
35775
50896
26327
49686
26989
2940
9851
54684
51129
13844
31658
22720
34964
46488
32841
33001
7138
32112
40410
827
8343
32024
18341
21020
13486
49260
36574
34669
44932
24739
29668
24745
23444
44458
55473
3322
22938
49447
38440
21033
21634
41018
7680
20195
46405
27033
15964
49976
7441
44359
42717
24010
35384
10493
31485
13130
9028
39249
48615
36264
21126
16217
29983
47291
6018
52284
883
17068
46405
30266
31735
44303
36775
14661
15244
49693
22647
32948
21023
46441
15859
6467
29328
1000
42947
46003
55599
12719
1061
49656
38577
33552
33027
5562
35878
5893
16515
5269
36239
18419
28474
27574
55769
52523
2426
50524
1131
3324
980
20469
1944
12449
45252
38881
3270
42108
34525
22168
10066
50154
1444
2937
32753
5043
22488
56060
30368


4441
54251
7110
20791
17623
8764
49416
1771
11097
15269
55598
255
42730
23683
5552
2183
22545
10810
11344
1378
2242
38294
15839
41479
19390
15786
35880
48373
40362
5589
7157
24685
2901
15450
33139
35504
7538
16863
44693
51966
17307
32731
13286
48949
40254
29802
53374
3993
30487
30490
36927
11557
27497
3739
48196
38392
42912
11732
44323
24786
42125
23493
39185
7151
15271
51395
13488
47614
35829
42320
16458
22648
54874
27974
13185
49165
51587
2624
16107
37650
54736
45141
9855
31961
20702
40392
6754
7674
42761
9394
31569
6682
45969
13723
43702
50206
49327
12171
50089
23953
43776
30974
54399
8003
41950
34903
13224
15139
15656
40162
16051
23452
49716
6271
11098
13841
8266
13220
23514
27465
30795
10805
53229
30261
23581
17155
31791
42788
22248
29076
7994
16357
27180
42538
12951
27065
11779
44096
39921
3317
24440
9017
32556
42664
39276
18448
45875
38639
48706
53090
26418
48417
17152
1230
22804
33214
10000
17474
37451
7728
30274
13345
24722
1106
47001
47995
22030
8446
31912
47177
2194
26750
32

34610
51884
49222
35248
14265
43103
40691
39136
39593
635
4241
26249
38361
27519
54364
27353
10591
55100
54053
49509
53499
3555
3307
7163
53957
10480
3434
39565
47841
3452
21281
53190
28454
5834
50753
24386
26875
17726
19578
28233
26919
856
29182
47171
49388
23739
50621
54580
11625
47113
49466
9071
50129
42694
28378
32879
23228
11218
9177
7058
7179
52326
25985
10379
43646
55700
5225
51924
48930
29554
40496
18051
26730
37560
37250
15803
34325
58
12832
33779
25749
9309
15648
40945
50195
6425
14684
35253
33821
31322
707
27155
31810
39507
34358
55119
15578
44218
53467
152
9229
9739
4913
35447
14045
55404
28940
7558
7893
55220
33487
42476
28503
8576
56078
31111
52930
26344
50722
23598
48424
9738
11809
26420
38032
18262
52126
7356
32897
48111
30207
33094
52840
50556
5012
54097
52448
8068
25697
51636
39395
54501
25177
51906
26831
19332
7902
12282
3363
13182
21358
11238
34457
10077
24113
35065
28837
24926
28185
16772
17836
48183
55434
40079
44909
21397
45762
40120
19840
24688
35963
9618
42258


5107
31756
41546
40883
19578
19202
53740
11718
618
3886
49222
13082
8087
6490
49402
43436
33044
29760
38404
25897
28462
40850
34883
719
10330
44971
19381
41491
29393
10429
14648
21667
23564
40005
1338
40489
18016
44078
9965
47780
35195
35249
51295
15698
24765
13684
12103
21244
43786
9297
48355
28347
32832
30369
582
49947
11303
50743
48562
14689
18441
10551
44081
4559
32894
14144
32250
25516
55617
37832
44671
5766
953
13231
45445
36600
30578
19210
11890
37588
32180
22319
9796
4398
4468
37245
34352
28352
29077
43352
53147
33899
31206
44364
49271
44035
43022
27770
16050
54669
22704
5647
21202
21909
52356
7183
3715
30183
11294
16195
38092
21145
54275
54867
46001
6954
15560
15625
11477
31395
48655
11980
54683
46449
726
34423
33979
14007
55295
50816
11615
53066
2034
49075
29750
12774
6330
12547
25553
16473
23031
3938
38699
44013
6360
10087
35034
9168
42095
15273
29363
47308
32202
29477
29781
44434
2238
49792
10670
8094
43903
23596
13118
52633
50450
16673
8480
23010
11618
38899
9948
44881
329

26251
26510
23278
2113
38768
27936
53956
31851
830
6617
17796
13751
48492
14890
18907
48385
48216
16956
8819
52660
47060
7609
35307
26816
26775
49490
20685
37147
50955
12211
6353
11517
43255
7839
20835
52960
48262
49073
29955
30959
23419
46430
7897
17902
4022
2977
38520
43480
7020
13463
11792
39579
43445
15765
14894
30485
45418
29776
37963
25598
11702
13467
44344
43883
41789
40257
32393
11205
30577
41704
51358
54950
38922
13832
44680
29349
10348
26091
20418
36164
13079
19434
53084
13321
37975
5475
41948
18550
21489
15667
45777
52455
17705
46881
45798
34174
42634
27305
32175
17213
49047
5219
52845
15412
13022
40945
26035
52044
55325
40190
38326
38208
26107
18332
47527
30096
5991
53880
25582
29687
26742
24083
15803
35838
55887
25478
27986
48984
21
28129
45043
14512
52059
54846
50936
25077
23398
7840
31844
51559
19747
26954
37932
28927
37055
34362
46225
3943
46408
28101
30883
11006
48255
41086
47866
30849
42435
34284
11972
54784
55287
8881
1522
49001
55255
48903
3780
44226
45095
48556
168

8603
43273
49627
14697
27467
53909
2436
1009
32785
32012
29854
1224
32552
47650
47003
10405
39064
19231
2344
23054
13083
2423
7366
55128
25797
54374
15569
23091
45526
11479
26604
5515
53751
25336
15750
2879
53206
26455
31324
33769
8657
47746
17433
24817
45461
51980
22569
8855
8177
9860
11739
20743
2800
33875
38680
17177
8506
42328
19827
47090
11184
17705
18676
609
48346
37518
12745
816
8406
11643
23098
285
42505
21306
24424
400
53494
19415
41710
45745
22409
52899
35428
558
9874
51216
55515
51055
33057
2451
2704
24270
5941
13523
16124
36707
15486
19364
23709
15702
5932
1286
15585
32364
3698
7729
14708
25740
48014
6722
13430
52364
11973
39710
49904
53181
30424
36835
5911
2275
14356
39356
35461
25755
748
9803
35813
21610
28486
35665
1258
2968
47589
7528
30778
2941
3085
52879
34004
7534
47502
44385
9115
38871
15337
55574
37662
16187
45088
46330
20433
819
837
20539
37077
41528
39298
38453
20372
51911
20609
10310
44154
54488
16619
50486
55548
1794
32845
5332
47372
52585
36677
31059
49667
152

13235
53870
4808
26866
48925
26222
55493
56027
4094
30918
49378
9008
13066
30026
8527
19266
19950
15254
53641
15130
34155
20677
39551
36429
34971
23871
7129
14772
41294
28785
40552
20895
55132
25658
18590
6596
7091
20535
27111
49481
44246
10254
4485
42673
2706
46694
52763
32773
20957
26052
51788
36223
53286
10012
10004
9240
52464
5117
5079
2724
10120
15921
18426
9603
21005
53816
43323
34753
48996
22520
35076
54952
50592
19159
53783
29331
3948
8498
26541
3336
16908
21884
45681
320
5057
53161
2942
6530
30755
15808
7369
27033
40515
16748
34573
52666
33594
53981
45927
46524
53921
12961
35060
21153
53465
16998
3031
10459
528
27723
20330
29365
40812
32371
53383
8094
54302
3665
37859
23882
46453
5928
22748
54937
36814
45115
38179
41511
51193
3996
46763
56087
47225
7106
31955
45740
44820
20337
6511
40334
50328
52540
28023
13878
50866
50002
411
47670
18842
50123
49128
8387
35881
7693
38851
31383
31663
21384
16979
15659
2206
25782
18910
30679
26859
23826
43485
17979
30438
28593
28982
12124
12505

9736
2695
36680
17012
6508
33306
11118
53657
23362
44301
13447
20517
30366
29726
12915
31678
48343
47437
48663
23987
40937
18269
42073
54812
52310
10861
29751
26705
21125
4418
50632
37298
52655
10725
10875
41172
32562
30128
43193
35500
8617
29883
34438
41835
1378
264
13435
38522
46330
27142
53598
42494
9448
2278
52459
21596
9687
53759
51314
25182
19066
52144
11648
7313
54275
23190
13581
43328
22095
7608
18153
6993
18821
22464
40181
44967
51771
15896
31417
7582
11554
7130
31573
23225
51345
23932
53407
2568
49986
29705
10867
744
19034
24148
11890
50333
5003
19525
2965
2624
14654
49897
51669
53044
7070
4927
46922
33911
38504
31155
55119
15269
49473
1421
45344
22582
16244
895
54074
43816
28129
2626
37119
17709
29130
37025
52507
7881
17462
43486
47980
44708
53569
17286
14029
5573
41835
14575
600
26789
34269
9406
15649
52930
21160
40458
21451
36456
6783
50477
6703
38500
49427
50729
30169
15400
17860
555
44083
13395
32330
32007
52836
9221
11864
44415
19210
10626
14907
49413
31053
31751
36873


5937
35566
45307
5678
24211
13460
34889
52132
55656
52483
45030
353
44099
17890
55188
40936
12324
55828
14982
38014
29630
48410
783
39261
21800
56018
52242
21480
44140
26726
4467
3604
36905
12779
43933
40103
24821
46705
48569
16034
22569
11538
33155
2519
10536
15682
2745
616
22830
34996
3358
24331
48340
1878
25858
51168
1380
6831
52192
30465
28713
2539
41263
24921
9558
20020
18028
1116
36536
24723
376
23575
47169
31333
11362
1289
36549
46026
55513
39724
10543
22893
7117
39412
15969
7112
49611
23946
32901
19888
16915
32228
22872
18756
4284
11834
53399
29811
34273
43635
38595
24183
11910
27332
34688
25681
29118
3494
7235
10189
40661
25107
9808
52423
50464
37841
22668
35430
14230
43510
14090
30405
56105
31493
48855
24844
37064
2743
8650
18885
4169
23794
35632
55336
14362
40172
43525
6084
39426
25356
32409
17533
46315
10455
16671
25060
17388
50707
49029
369
55389
25283
33527
7385
17724
8668
53575
21516
55646
219
21476
54188
56061
7544
40209
36298
31672
28622
5532
47063
48418
39820
33311
40

14629
24324
16006
56156
39277
21744
35869
49085
48858
45066
36319
35189
34631
27206
33241
49228
27052
20302
41268
21813
35081
18388
25862
6031
27562
36606
29307
45946
30493
11638
30106
17014
47559
41328
51287
29492
33860
47747
46057
23185
9573
43682
49603
39451
33371
30803
41411
11557
42627
17008
9171
38438
17546
47257
6804
25213
52176
29763
48380
27493
11177
37428
51583
21529
5234
54399
5557
21497
50406
32754
34384
34771
335
21872
43279
27196
35200
49834
21671
10615
18230
26745
33831
14298
4523
38095
45843
6155
26380
49760
11167
19856
45617
34894
35752
12261
14970
5263
14916
31229
32544
26748
22292
31445
31641
17697
22264
50613
47227
43877
20402
34300
55501
25683
17689
47186
45488
46831
32934
44039
48797
16067
20733
43858
31596
32206
37361
40958
35796
35798
27438
20501
26562
50807
1407
39224
4813
47961
5778
34118
6079
24470
27225
3751
277
10007
30460
29286
53914
16255
12069
43774
18026
41325
39678
38123
25033
49449
29188
16532
32313
42355
6758
14226
20030
46579
20564
20712
7432
23960


32656
7437
44487
23588
18285
39162
46156
14431
28109
47878
33721
19529
48022
52972
26830
3409
20233
4770
10063
54333
28497
51616
2163
15666
34296
1007
28880
53412
263
25838
13997
52585
3648
41438
42511
27559
29253
32945
55826
33768
26378
8827
6350
41677
44789
19106
37583
20545
34884
19734
47085
6512
15741
2757
40690
27421
47283
23277
35683
44120
37630
27176
43993
51010
25550
43557
42299
47289
47736
32092
2188
40534
27776
23684
40522
49475
20836
6741
32899
31200
15384
54054
3680
17697
6525
50363
37232
36215
13925
39199
5920
15274
55777
50756
14112
40033
11119
7773
1427
16163
12685
12832
8948
30889
15210
37228
36644
37848
4909
32922
1159
3212
47512
161
6881
19564
10055
30898
53921
39372
8244
4789
24368
36618
44205
18821
15232
33035
7520
45359
29030
46635
1747
38066
9329
4847
3377
930
47660
18330
44642
40306
46242
8011
7672
34108
34313
42519
38725
38654
45923
46754
27361
54599
39798
1648
35494
10646
47599
51040
39623
43331
3260
12244
11254
19859
11093
23062
6760
18149
7142
37517
19908
134

21267
43115
26001
20401
3216
3855
26790
29111
33932
31742
12773
1234
27593
229
38879
16948
13796
15270
24380
32017
26067
30233
12890
5505
5336
30659
27047
3682
41004
19920
49479
38538
13420
1974
44231
14502
54051
7276
1301
20623
1008
11342
39461
26673
7241
28100
43747
51380
2669
18361
36578
1697
27202
17092
4865
8360
54567
42590
48300
49940
52395
34451
2391
2214
54956
13012
8421
51319
51101
29123
16098
3123
43431
25439
15422
6549
27674
15084
48654
40086
7106
32814
5905
8312
15216
15330
50427
54767
20749
44974
26111
7393
10690
12183
20716
6402
17527
23400
36490
51412
35045
12364
25317
14163
51818
41510
51556
33018
38194
51910
37914
8604
2304
55466
36933
50324
46317
48230
36746
41572
21730
40576
18664
21145
38547
27769
43797
34618
4960
46194
13541
16817
50917
32073
55953
43917
2097
33949
16425
48638
48323
15963
23592
42373
31208
48929
23784
21322
52120
2327
13481
28708
11027
54232
31697
13468
805
39761
5023
2333
8916
36118
32029
53020
33818
39116
8918
54060
53456
25640
43384
20593
44037


30606
38379
11714
41430
19657
31945
45453
13159
44545
39086
21942
55172
29065
25053
34151
12336
50261
15610
42740
48663
14948
54953
5487
51233
8693
891
39012
41233
18183
5316
54549
1064
23554
42653
22294
3269
48500
51125
33550
15228
689
11065
2340
27832
13723
37140
7210
45485
22633
47504
37664
13427
26717
27261
9983
42574
2926
52055
41621
21285
10173
1285
5629
54628
49967
50271
51561
37660
30926
50197
1874
40442
27605
36143
52155
36296
52499
14497
33710
5248
43245
16900
3933
49732
14347
7692
14245
19071
26852
8842
44675
3855
30915
33159
4061
47767
6595
43580
815
13097
18246
25876
21664
5418
23751
5661
29487
51931
50705
34123
54146
12391
54792
6138
15296
8019
18047
38704
26218
51525
21209
11592
10391
31401
48661
48768
46069
32674
35031
12549
31455
54095
6406
38585
39201
48373
24815
45893
53597
51711
37691
51118
46434
31675
55909
36247
36020
1752
19937
42749
39422
16513
55173
45057
48344
40116
44600
13329
18853
75
404
38837
36762
31211
55342
21117
48958
8229
988
23359
35173
5445
35514
38

24133
29753
34018
30824
4600
15336
48942
52695
18817
17979
30137
50708
4674
42774
5770
27576
21658
17885
35894
26357
1097
12280
2411
36561
15767
38562
51128
7278
16064
40655
50530
27084
1994
15614
27269
53875
52299
9200
29447
16751
35667
25051
24513
840
31051
48416
27588
42063
45403
55712
13624
50327
53220
7342
12279
46428
46405
33897
37068
28161
55010
4139
44517
18996
2436
14420
55979
44414
38594
32172
14784
21086
45421
14120
9191
24038
10382
32720
55364
36661
5397
43529
23394
25657
36044
11821
11043
16236
42602
50916
987
53374
27018
48372
11106
19867
14894
25194
47166
19078
54227
55041
22111
7809
34507
10700
36962
25447
1842
4322
16084
42833
26735
12931
11830
44717
54822
8135
23911
4927
54466
8201
14290
13814
55835
22297
3972
26686
4834
4332
55300
48267
33916
5485
43758
7958
28338
55309
13107
53335
49006
31832
25212
1894
37244
44744
27242
46788
14170
27802
2141
45631
11236
12705
9667
43897
24864
27090
3424
55977
36209
5982
27923
45767
29853
40962
39413
1338
23548
36742
13890
18244
41

6311
32602
20627
47349
43459
28350
51314
51998
36825
55027
39909
52419
44979
53533
39669
40122
13345
18175
29718
15719
42893
14167
30312
1971
30610
42097
47909
27094
53891
46972
48411
43807
17189
24370
40682
28020
46930
41632
32947
5137
32863
10303
34491
13461
20229
31111
42841
33827
36993
2445
4907
1903
16181
9298
33347
33572
4499
20179
52347
32628
38987
55941
1472
2862
27593
47115
33113
43588
41444
598
18972
24689
39049
7297
22501
25376
9941
43046
11545
45579
13073
38247
8303
54480
5007
24896
28453
32488
20908
554
54684
28372
52339
13487
18189
6924
21976
43243
40786
17806
54078
38988
17049
17722
4218
35457
33351
7380
2041
40882
6940
1420
27913
32517
14725
45917
33691
28636
20356
10187
46576
12853
13589
55080
48342
22402
29902
22521
30854
10568
33217
17743
7884
42084
14739
31718
6788
27604
38616
11939
5605
39689
29444
18382
40129
41595
43296
34158
25270
44489
15879
53238
23357
32051
390
43680
5130
4809
39299
21826
15486
33628
52199
54137
9032
22632
36789
15124
8801
54694
46474
45599
4

37231
52214
10187
21415
18698
41363
55020
5252
53346
49683
38041
26736
40594
48810
39587
16556
13008
48458
37134
51403
39991
15059
1115
34594
12787
47716
35102
40966
25990
14286
54098
4185
41204
32608
21965
42905
27397
53052
46090
48021
16101
52129
1941
46099
6394
30973
47246
38225
12671
20155
20119
14252
42308
42477
35065
49095
26656
33564
755
44957
40918
30967
41951
14644
53581
8264
23387
876
41148
32462
36465
26480
1251
36539
8664
2079
20678
22543
9213
5132
4596
17949
3731
19995
28824
9898
41689
3051
32228
38974
7386
40046
48358
48867
37018
29792
13553
38303
51778
22967
3984
6894
27918
23092
41963
54907
23512
40781
54639
12818
1405
15083
21306
21479
45491
6248
42795
49867
39433
14059
19464
15455
35190
47140
46519
47941
47956
36857
36819
28809
55194
11183
13680
32391
6081
6541
8867
44625
51269
31930
47285
3780
54841
40229
48390
13098
54739
16128
53176
20509
23756
341
48847
29424
20222
50593
30672
34525
34258
40651
1694
16972
21268
16319
21266
11352
2289
1671
37313
51615
27453
40467
4

20456
7467
55951
21141
19402
39601
53713
22978
48418
31534
15396
25892
422
27974
54320
4004
42449
35465
323
29831
17132
33770
26634
32837
52663
38963
14152
13671
14675
47215
14517
29511
30867
4612
42806
14
19959
23520
27027
16406
17271
25691
40152
49133
50063
12591
8730
18679
33201
21095
49800
44280
50108
21772
17831
38107
32665
49813
20572
5520
4218
23358
18860
7449
48946
43153
23403
43424
44681
31839
40922
25169
4001
35115
872
30505
52486
12543
32216
49506
11018
44250
34900
49923
17324
54006
7295
1874
29786
32224
11561
49105
46029
10998
45937
8142
43375
14443
32466
16757
16778
38932
7163
1953
13736
25204
51899
22616
25964
18101
4261
50483
15721
20292
6564
12559
46353
7104
25120
17255
3608
12177
9228
48380
26199
27286
1044
25190
54828
27987
21796
20621
9899
16972
42209
50709
26832
17077
30540
34627
41201
49653
11804
14137
33508
54372
30304
15335
608
6608
54203
14172
43223
33737
28375
30474
34467
6560
25858
30014
44869
7694
31789
24510
19915
743
12916
38744
54297
16521
51435
27536
5323

19638
150
13875
36187
26913
41405
10162
8796
33487
46200
10425
12347
52012
185
13593
21008
32336
37025
21028
22555
48968
41427
41160
14805
48099
11704
8203
39312
49609
24211
42488
48884
39801
17422
464
47677
38720
44768
32239
33844
31383
7739
29948
5671
28734
27822
51294
22547
30772
12493
25006
32506
34
39268
44188
33199
13340
49186
12755
28988
41998
29262
10309
27649
13214
2975
6062
22524
50073
10025
45997
3767
35707
5023
15499
52952
14509
46226
31237
9444
14759
49575
38117
42568
14106
20791
11353
33836
50345
51016
9354
37815
25872
6509
35121
29102
22951
28450
9073
20595
49587
28557
43527
9323
29553
24232
43400
30817
29180
42907
19091
43457
32800
38523
50157
20837
10582
48983
9471
10567
23060
46260
24296
49089
45557
27098
38080
44451
12709
49640
12204
55382
17417
47401
33036
1146
39277
5771
47493
51186
9814
18400
26877
12218
54906
47257
23605
53952
10091
49081
6731
55228
5340
37333
6965
39611
39427
40935
44001
431
45900
29786
36291
49930
39148
25062
45190
33653
9291
46980
43821
13498


26081
30166
45671
30524
49636
13692
51411
46126
32459
38941
40904
18922
37527
10469
12329
28022
12552
7434
47638
14878
12378
20242
15376
27762
15881
54884
37067
32230
47600
20181
23097
37732
10647
3485
13186
48559
39265
10830
35299
29451
52042
6089
52781
11514
4652
1095
30450
27923
6897
3082
27335
49547
11126
11177
42182
6888
29712
46215
13583
3105
29167
43274
50192
2209
44215
37432
13346
52962
17278
7884
31614
32403
24896
24224
2533
13883
38467
6321
35682
27164
26451
15268
11021
30015
54251
39849
21546
42463
34993
53056
54982
24961
27017
3388
7968
11878
44512
14863
31102
48121
7885
32588
30714
2206
48707
39255
2768
54672
8108
41903
49405
51637
50004
13875
23576
53361
1286
51675
7724
28350
51829
36111
32148
49786
45382
7529
29161
19300
6033
43438
50176
35789
47164
20985
49807
42920
39794
53561
28227
30514
54715
2610
53962
6343
25184
29788
23970
53008
54520
39229
29328
53887
49102
55005
3703
28183
4844
48398
50243
16008
32617
46200
47651
9630
46891
2590
21361
31454
53490
54081
51528
234

35373
51517
19876
7745
45775
6795
20120
23914
30529
25590
2502
52002
23739
50846
31931
12127
55669
8881
50252
34163
44011
24159
27217
46472
9599
27199
34484
30903
41471
7248
54166
42673
38357
13359
23404
40937
33275
3777
45677
8963
43688
53891
39639
48359
44136
25986
31742
21705
44044
32817
36985
56116
15603
27052
32323
29119
35886
30532
49688
54203
26240
27
4399
26369
21009
10010
7279
21101
38144
32190
14274
40386
52370
401
19932
18869
40045
36271
50819
50072
37108
19331
54338
33805
43726
1941
50360
38799
12104
44807
50442
22615
44320
28969
12860
50697
30520
39965
10674
4119
5397
30453
2614
39278
10893
10308
53932
34469
13208
38706
13898
52582
16840
4152
40509
33863
44976
47574
10865
39678
40961
22370
52485
25444
19340
37682
39466
51805
26722
48886
144
17456
15430
419
16820
29449
16668
55716
53873
42808
50697
28808
6919
33132
24663
13237
12340
6455
12322
15040
52231
30126
2498
24492
32693
38489
20143
6696
54698
39551
7703
8171
48487
14660
24962
47630
3201
5482
38750
53290
4199
19249
2

9407
39289
23614
39017
22574
40857
4096
54077
30611
7984
14695
38741
16624
25331
20610
41759
30202
55699
44824
24060
54039
31184
48526
40384
46211
6802
54484
17772
4739
36751
24431
23358
16228
53661
26245
50338
20805
24887
27626
21908
42768
32067
3463
15062
18368
55639
14691
25540
51089
9441
19585
32870
16093
14635
35696
22343
2174
4130
11738
30129
17471
46020
17877
11810
11556
42907
2369
26095
53933
12091
43537
44590
31817
46351
13000
40401
23196
31174
4476
27434
55528
3768
6423
56133
8987
53060
5180
52283
35932
46495
1494
20673
37054
53977
9107
36218
41481
39890
33236
24607
5837
54774
9274
37326
17851
55091
12201
12046
15225
3442
10753
38810
48562
28663
39051
31172
3946
23563
28437
17317
14988
27898
55196
62
5958
30971
23965
54444
16851
34305
15932
2427
37073
26665
7855
55187
22966
72
37389
31666
21490
34126
54679
55290
53377
20035
43164
27995
6845
12425
41289
4029
20564
44685
45610
41138
55643
36753
50776
42505
35554
2236
50497
42783
25832
17205
524
55489
53477
13456
41275
34349
241

23117
19961
34258
47438
3521
16795
6684
20448
33339
38041
10464
31342
34342
30516
39553
27095
17579
19495
29606
39473
36493
36839
26357
6264
21099
2751
10862
54554
31651
24856
55427
2187
44
33422
36674
53720
3815
34269
3399
28267
54380
38520
51083
52794
15527
7178
40137
21876
36510
37713
28838
18878
18320
3442
54496
31908
22448
34956
47997
32626
6390
25765
44351
18834
5021
10704
6629
31496
53186
51264
37754
37967
47862
30982
44833
16087
33542
10507
12467
49187
54496
40951
27525
10781
14058
9272
8636
10997
47699
47448
38949
31242
21425
43472
26771
28131
29561
3495
45622
45692
11329
39223
21278
17821
55568
3739
1326
29711
53722
5035
17195
45841
49071
40437
24257
24192
15202
24054
30738
38531
21443
10198
22691
12447
10651
13823
2363
15059
17054
4986
15541
13433
52936
23956
42921
14940
4810
12699
13912
3109
14693
51613
54232
50236
24485
19349
22556
24596
39888
17899
30162
27747
49620
36729
17914
43345
35236
53349
41890
55763
29672
7383
47972
45389
47639
25620
11083
21310
12780
10130
44312


22316
42464
21657
16904
55372
6225
35564
7778
52188
29075
16812
15163
9129
45115
50933
8612
46141
21266
38630
22796
18362
22908
21321
46822
48367
1755
33061
26401
44590
30508
20945
36470
39731
52994
43680
9418
32743
33905
8051
48576
44547
40480
46597
45886
26298
29467
55412
31723
18279
47383
20387
46718
5523
28195
49793
27831
5051
17139
46939
18972
7159
53936
43684
7062
9473
5055
7982
40634
50739
37395
50822
21045
31799
10919
14156
15201
53103
24077
18087
44228
35307
56160
12447
40372
54179
40461
12185
25921
31803
5332
18781
14636
31296
26531
18735
37626
5884
44889
53927
13999
13255
55973
49643
36177
43493
40031
6150
53571
14474
3574
14855
7133
55974
45021
42320
1727
8020
407
35638
19699
53182
52815
36223
10998
23126
11555
51929
15038
10822
34514
3154
55671
6130
8799
29293
17718
30682
18388
52849
18606
40469
11379
36469
430
9044
17543
41466
36086
343
42738
25575
25876
43908
50623
7736
24286
21910
11935
13628
13297
14151
38327
38855
37563
17169
11666
54688
44041
31797
28692
48817
40990


27614
22617
32478
11165
42742
28276
28238
42352
49371
44179
15373
4236
45645
11005
14723
28145
16768
46856
45412
39979
36219
9611
11381
7518
29083
53183
2007
40979
16026
23262
13046
9916
24082
46625
52499
37882
4194
37314
44189
52819
5198
34191
6654
27415
27484
5714
16588
53894
41266
28382
53972
40577
49965
23284
3551
2109
37778
16569
1540
43272
41045
10817
20700
40480
11533
26745
5127
32746


In [4]:
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import floyd_warshall


N,M = map(int,input().split())
graph=np.zeros((N,N),int)
for _ in range(M):
    a,b=map(int,input().split())
    graph[a-1,b-1]=1
    graph[b-1,a-1]=1




graph = csr_matrix(graph)
dist_matrix, predecessors= floyd_warshall(csgraph=graph,unweighted=True, directed=False,return_predecessors=True)

if -9999 in predecessors[0][1:]:
    print("No")
else:
    ans=predecessors[0][1:]+1
    print("Yes")
    for a in ans:
        print(a)

Yes
6
5
5
1
1


array([6, 5, 5, 1, 1], dtype=int32)

In [63]:
A,B,H,M = map(int,input().split())

import math

x=abs(H/12+1/12*M/60-M/60)
x=min(x,1-x)
theta=2*math.pi*x
c=A**2+B**2-2*A*B*math.cos(theta)
print(math.sqrt(c))

4.564257194330057


In [62]:
math.sqrt(c)-4.56425719433005567605


1.7763568394002505e-15

In [23]:
K=int(input())
S=input()
if len(S) >=K:
    res=S[:K]
    res+="..."
    print(res)
else:
    print(S)

ferelibenterhominesidquodvoluntcredunt


In [13]:
N=input()
x=int(N[-1])
if x in [2,4,5,7,9]:
    print("hon")
elif x == 3:
    print("bon")
else:
    print("pon")

hon


In [9]:
import numpy as np
import bisect

def position_in_neg(x):
    # y=n_pos-np.searchsorted(A_pos,x//A_neg,side='right')
    res=0
    for y in x//A_neg:
        res+=n_pos-bisect.bisect_right(A_pos, y)
    return res

def position_in_pos(x):
    # z=np.searchsorted(A_pos,-(-x//A_pos),side='left')
    # w=np.searchsorted(A_neg2,-(-x//A_neg2),side='left')
    res=0
    for y in -(-x//A_pos):
        res+=bisect.bisect_left(A_pos, y)
    for y in -(-x//A_neg2):
        res+=bisect.bisect_left(A_neg2, y)
    tmp=len(A_pos[A_pos**2<x])+len(A_neg2[A_neg2**2<x])
    return (res-tmp)//2

def position(x):
    if x<0:
        return position_in_neg(x)
    elif x==0:
        return n_pos*n_neg
    else:
        return position_in_pos(x)+n_pos*n_neg+(n_pos+n_neg)*n_zero+n_zero*(n_zero-1)//2


def resolve():
    N,K=map(int,input().split())
    A=list(map(int,input().split()))

    A=np.array(A)
    global A_pos,A_neg,A_neg2,n_pos,n_neg,n_zero
    A_pos=np.sort(A[A>0])
    A_neg=np.sort(A[A<0])
    A_neg2=-A_neg[::-1]
    n_pos=len(A_pos)
    n_neg=len(A_neg)
    n_zero=N-n_pos-n_neg


    l=-pow(10,18)
    r=pow(10,18)
    while(r-l>1):
        mid=(l+r)//2
        if position(mid)<K:
            l=mid
        else:
            r=mid
    print(l)

if __name__ == "__main__":
    resolve()

-6


In [8]:
position_in_neg(-12)

4

In [7]:
import numpy as np
N,K=map(int,input().split())
A=list(map(int,input().split()))

A=np.array(A)

A_pos=np.sort(A[A>0])
A_neg=np.sort(A[A<0])
A_neg2=-A_neg[::-1]
n_pos=len(A_pos)
n_neg=len(A_neg)
n_zero=N-n_pos-n_neg

def position_in_neg(x):
    y=n_pos-np.searchsorted(A_pos,x//A_neg,side='right')
    return y.sum()

def position_in_pos(x):
    z=np.searchsorted(A_pos,-(-x//A_pos),side='left')
    w=np.searchsorted(A_neg2,-(-x//A_neg2),side='left')
    tmp=len(A_pos[A_pos**2<x])+len(A_neg2[A_neg2**2<x])
    return (z.sum()+w.sum()-tmp)//2

def position(x):
    if x<0:
        return position_in_neg(x)
    elif x==0:
        return n_pos*n_neg
    else:
        return position_in_pos(x)+n_pos*n_neg+(n_pos+n_neg)*n_zero+n_zero*(n_zero-1)//2

l=-pow(10,18)
r=pow(10,18)
while(r-l>1):
    mid=(l+r)//2
    if position(mid)<K:
        l=mid
    else:
        r=mid
print(l)

-6


In [6]:
-A_neg[::-1]

array([2, 4])

In [391]:
np.flip([1,2,3,4,5,6,7])

array([7, 6, 5, 4, 3, 2, 1])

In [2]:
    def numTest(x):
        if x.isdigit():
            return x
        else:
            return "Not a number!"

In [3]:
numTest(12313)

AttributeError: 'int' object has no attribute 'isdigit'

In [360]:
import numpy as np

# x未満のA[i]*A[j]の数
def count_pair(x):
    # A内のペアで積がxより小さいものの個数
    # まず(i,j)と(j,i)を重複して数える
    cnt = 0
    # B=x/A[i]はA[j]の候補
    # A[i]<0なる各iに対してA[j]>x/A[i]なるA[j]達の位置
    p=np.searchsorted(A, x//A_nega, side='right')
    # 上のA[j]達より大きいAの要素
    p=N-p
    # 上のA[j]達より大きいAの要素の数
    cnt += p.sum()
    if x > 0:
        # 各iに対してA[j]=0なるjの個数
        cnt += len(A_zero)*N
    # A[i]>0なる各iに対してA[j]<x/A[i]なるjの個数
    cnt += np.searchsorted(A, -(-x//A_posi), side='left').sum()
    # i=jを除いてから2で割る
    cnt = (cnt-(A**2 < x).sum())//2
    return cnt


# count_pair(x)<Kをみたすxの最大値を二分探索で求める
N, K = map(int, input().split())
* A, = map(int, input().split())
A = np.array(A)
A = np.sort(A)
A_posi = A[A > 0]
A_zero = A[A == 0]
A_nega = A[A < 0]
inf = 10**18+1
l, r = -inf, inf
# しゃくとり法
while r - l > 1:
    c = (l + r) // 2
    if count_pair(c) < K:
        l = c
    else:
        r = c
    print(l,r)
print(l)



0 1000000000000000001
0 500000000000000000
250000000000000000 500000000000000000
375000000000000000 500000000000000000
437500000000000000 500000000000000000
437500000000000000 468750000000000000
437500000000000000 453125000000000000
445312500000000000 453125000000000000
445312500000000000 449218750000000000
447265625000000000 449218750000000000
448242187500000000 449218750000000000
448242187500000000 448730468750000000
448242187500000000 448486328125000000
448242187500000000 448364257812500000
448242187500000000 448303222656250000
448272705078125000 448303222656250000
448272705078125000 448287963867187500
448280334472656250 448287963867187500
448280334472656250 448284149169921875
448282241821289062 448284149169921875
448283195495605468 448284149169921875
448283195495605468 448283672332763671
448283195495605468 448283433914184569
448283195495605468 448283314704895018
448283255100250243 448283314704895018
448283255100250243 448283284902572630
448283270001411436 448283284902572630
4482832

In [15]:


import numpy as np
N,K=map(int,input().split())
A=list(map(int,input().split()))

A=np.array(A)

A_pos=np.sort(A[A>0])
A_neg=np.sort(A[A<0])
A_neg2=np.sort(-A_neg)

np=len(A_pos)
nn=len(A_neg)
nz=N-np-nn
n_post=np*(np-1)//2+(nn*(nn-1))//2
n_zero=nz*(np+nn)+nz*(nz-1)//2
n_neg=np*nn



#array内で積がx未満になるペアの数
def syakutori_pos1(x):
    res=0
    j=np-1
    y1=-(-x//A_pos)
    for i in range(np):
        tmp=0
#         j=n-1

        while j!=-1:
            
            if A_pos[j]>=y1[i]:
                j-=1
            else:
                break
        
        tmp+=j+1
        if A_pos[i]**2<x:
            tmp-=1

        res+=tmp
    res=res//2
    return res


def syakutori_pos2(x):
    res=0
    j=nn-1
    y2=-(-x//A_neg2)
    for i in range(nn):
        tmp=0
#         j=n-1

        while j!=-1:
            
            if A_neg2[j]>=y2[i]:
                j-=1
            else:
                break
        
        tmp+=j+1
        if A_neg2[i]**2<x:
            tmp-=1

        res+=tmp
    res=res//2
    return res


#array内で積がx未満になるペアの数

def syakutori_neg(x):
    yn=x//A_neg
#     print(A_pos,y)
    res=0
    i=0
    j=np-1
    for z in reversed(yn):
        while(j!=-1):
            if z<A_pos[j]:
                j-=1
            else:
                break
#         print(z,j+1)
        res+=j+1
    return np*nn-res



def syakutori(x):
    if x>0:
        return syakutori_pos1(x)+syakutori_pos2(x)+n_neg+n_zero
    elif x==0:
        return n_neg
    else:
        return syakutori_neg(x)




r=10**18
l=-10**18
while(r-l>1):
    mid=(l+r)//2
    z=syakutori(mid)
#     z= count_pair(mid)
#     print(l,r)
    if z < K:
        l=mid
    else:
        r=mid
print(l)

-6


In [12]:
syakutori(-2)

4

In [10]:
count_pair(-10)

NameError: name 'count_pair' is not defined

In [1750]:
#array内で積がx未満になるペアの数
def syakutori_neg2(x,array_pos,array_neg):
    n_pos=len(array_pos)
    n_neg=len(array_neg)
    y=x//array_neg
#     print(A_pos,y)
    res=0
    i=0
    j=n_pos-1
    for z in reversed(y):
        while(j!=-1):
            if z<array_pos[j]:
                j-=1
            else:
                break
#         print(z,j+1)
        res+=j+1
    return n_pos*n_neg-res

In [1782]:
x=-30

In [1783]:
syakutori_neg(x,A_pos,A_neg)

0

In [1784]:
syakutori_neg2(x,A_pos,A_neg)

[3 5] [ 7 15]
15 2
7 2


0

In [1603]:
A_pos=[3,5]
A_pos=np.array(A_pos)

In [1515]:
A_neg

array([-4, -2])

In [1447]:
A_neg

array([-4, -2])

In [1231]:
if K<n_neg:
    print("neg")
    syakutori_neg()
elif n_neg<=K and K< n_neg+n_zero:
    print(0)
else:
    print("pos")
    k=K-n_neg-n_zero

pos


In [480]:
A_pos

[1, 3, 3, 8, 9, 11]

In [526]:
x=10

In [527]:
res=0
right=0
count=0
for left in range(n-1):
    while(right < len(A_pos)-1 and A_pos[left]*A_pos[right+1]<x):
        right+=1
    print(left,right, A_pos[left]*A_pos[right])
    res=max(res,right - left)
    if left<right and A_pos[left]*A_pos[right]<x:
        count+=right - left
    if left == right:
        right+=1

0 4 9
1 4 27
2 4 27
3 4 72
4 4 81
5 5 121


In [528]:
count

4

In [537]:
n,k=map(int,input().split())
arr=list(map(int,input().split()))
arr=sorted(arr)
nc=0
zc=0
pc=0
for i in range(n):
  if arr[i]<0:
    nc+=1
  elif arr[i]==0:
    zc+=1
  else:
    pc+=1
ncc=nc*pc
zcc=zc*(nc+pc)+(zc*(zc-1))//2
pcc=(nc*(nc-1))//2+(pc*(pc-1))//2
if k<=ncc:
  arr1=[]
  arr2=[]
  for i in range(n):
    if arr[i]<0:
      arr1.append(-arr[i])
    elif arr[i]>0:
      arr2.append(arr[i])
  arr1=arr1[::-1]
  c1=len(arr1)
  c2=len(arr2)
  l=0
  r=10**18+1
  k=ncc-k
  while r-l!=1:
    mid=(l+r)//2
    cnt=0
    pos=c2-1
    for i in range(c1):
      while pos!=-1:
        if arr2[pos]>mid//arr1[i]:
          pos-=1
        else:
          break        
      cnt+=pos+1
    if cnt>k:
      r=mid
    else:
      l=mid
  print(-r)
elif k<=(ncc+zcc):
  print(0)
else:
  arr1=[]
  arr2=[]
  for i in range(n):
    if arr[i]<0:
      arr1.append(-arr[i])
    elif arr[i]>0:
      arr2.append(arr[i])
  arr1=arr1[::-1]
  c1=len(arr1)
  c2=len(arr2)
  l=0
  r=10**18+1
  k-=(ncc+zcc)
  while r-l!=1:
    mid=(l+r)//2
    cnt1=0
    pos1=c1-1
    for i in range(c1):
      tmp=0
      while pos1!=-1:
        if arr1[pos1]>mid//arr1[i]:
          pos1-=1
        else:
          break
      tmp+=pos1+1
      if arr1[i]**2<mid:
        tmp-=1
      cnt1+=tmp
    cnt1=cnt1//2
    cnt2=0
    pos2=c2-1
    for i in range(c2):
      tmp=0
      while pos2!=-1:
        if arr2[pos2]>mid//arr2[i]:
          pos2-=1
        else:
          break
      tmp+=pos2+1
      if arr2[i]**2<mid:
        tmp-=1
      cnt2+=tmp
    cnt2=cnt2//2
    cnt=cnt1+cnt2
    if cnt>=k:
      r=mid
    else:
      l=mid
  print(r)


6


In [531]:
arr1=[]
arr2=[]
for i in range(n):
if arr[i]<0:
  arr1.append(-arr[i])
elif arr[i]>0:
  arr2.append(arr[i])
arr1=arr1[::-1]
c1=len(arr1)
c2=len(arr2)
l=0
r=10**18+1
k=ncc-k
while r-l!=1:
mid=(l+r)//2
cnt=0
pos=c2-1
for i in range(c1):
  while pos!=-1:
    if arr2[pos]>mid//arr1[i]:
      pos-=1
    else:
      break        
  cnt+=pos+1
if cnt>k:
  r=mid
else:
  l=mid
print(-r)

IndentationError: expected an indented block (<ipython-input-531-3642cf2a60bd>, line 4)

In [553]:
  n,k=map(int,input().split())
  arr=list(map(int,input().split()))
  arr=sorted(arr)
  nc=0
  zc=0
  pc=0
  for i in range(n):
    if arr[i]<0:
      nc+=1
    elif arr[i]==0:
      zc+=1
    else:
      pc+=1
  ncc=nc*pc
  zcc=zc*(nc+pc)+(zc*(zc-1))//2
  pcc=(nc*(nc-1))//2+(pc*(pc-1))//2
  arr1=[] # 負の数
  arr2=[] # 正の数
  for i in range(n):
    if arr[i]<0:
      arr1.append(-arr[i])
    elif arr[i]>0:
      arr2.append(arr[i])


In [554]:
arr

[-1, 0, 0, 0, 0, 0, 2, 3, 4, 5]

In [555]:
arr1

[1]

In [556]:
arr1=arr1[::-1]

In [549]:
arr2

[2, 3, 4, 5]

In [543]:
  
  c1=len(arr1)
  c2=len(arr2)
  l=0
  r=10**18+1
  k-=(ncc+zcc)
  while r-l!=1:#２分探索
    mid=(l+r)//2
    cnt1=0
    pos1=c1-1
    for i in range(c1):
      tmp=0
      while pos1!=-1:
        if arr1[pos1]>mid//arr1[i]:
          pos1-=1
        else:
          break
      tmp+=pos1+1
      if arr1[i]**2<mid:
        tmp-=1
      cnt1+=tmp
    cnt1=cnt1//2
    cnt2=0
    pos2=c2-1
    for i in range(c2):
      tmp=0
      while pos2!=-1:
        if arr2[pos2]>mid//arr2[i]:
          pos2-=1
        else:
          break
      tmp+=pos2+1
      if arr2[i]**2<mid:
        tmp-=1
      cnt2+=tmp
    cnt2=cnt2//2
    cnt=cnt1+cnt2
    if cnt>=k:
      r=mid
    else:
      l=mid
  print(r)




6


In [591]:
mid=10000

In [592]:
cnt2=0
pos2=c2-1
for i in range(c2):
    tmp=0
    while pos2!=-1:
        if arr2[pos2]>mid//arr2[i]:
            pos2-=1
        else:
            break
    tmp+=pos2+1
    if arr2[i]**2<mid:
        tmp-=1
    cnt2+=tmp
cnt2=cnt2//2



In [593]:
cnt2

6

In [1288]:
#array内で積がx未満になるペアの数
def syakutori_pos(x,array):
    n=len(array)
    res=0
    j=n-1
    for i in range(n):
        tmp=0
#         j=n-1
        y=-(-x//array[i])
        while j!=-1:
            
            if array[j]>=y:
                j-=1
            else:
                break
        
        tmp+=j+1
        if array[i]**2<x:
            tmp-=1
        res+=tmp
    res=res//2
    return res



#array内で積がx未満になるペアの数
def syakutori_neg(x,array_pos,array_neg):
    n_pos=len(array_pos)
    n_neg=len(array_neg)
    y=-(-x//array_neg)
    print(array_pos)
    print(y)
    res=0
    j=0
    k=-1
    for i in range(n_pos):
        tmp=0

        while k<n_neg-1:     
            if y[k+1]<=array_pos[i]:
                k+=1
            else:
                break
        j=max(j,k)
        while j<n_neg-1:
            if array_pos[i]<=y[j]:
                j+=1
            else:
                break
        print(k,j)
        res+=j-k
    print(res)
    return n_pos*n_neg-res

In [1289]:
syakutori_neg(-15,A_pos,A_neg)

[2 3 4 5]
[ 5 15]
-1 1
-1 1
-1 1
0 1
7


1

In [1268]:
A_pos

array([2, 3, 4, 5])

In [1269]:
A_neg

array([-3, -1])

In [461]:
n=7
K=6
a=[4,3,1,1,2,10,2]

In [462]:
res=0
right=0
mul=1
for left in range(n):
    while(right < n and mul*a[right]<=K):
        mul*=a[right]
        right+=1
    res=max(res,right - left)
    if left == right:
        right+=1
    else:


In [692]:
arr=np.array(arr)

In [693]:
import bisect

In [796]:
x=8

In [798]:
#x以下のペアの数
n=len(arr)
res=0
for i in range(n):
    b=x//arr[i]
    j=bisect.bisect_right(arr, b)
    res+=j
for j in range(n):
    if arr[j]**2<=x:
        res-=1
print(res,res//2)

6 3


In [795]:
res

10

In [802]:
x=9

In [805]:
#x未満のペアの数
n=len(arr)
res=0
for i in range(n):
    b=x//arr[i]
    j=bisect.bisect_left(arr, b)
    res+=j
    print(b,i,j,n-j)
for j in range(n):
    if arr[j]**2<x:
        res-=1
print(res,res//2)

9 0 4 2
3 1 1 5
3 2 1 5
1 3 0 6
1 4 0 6
0 5 0 6
5 2


In [361]:
def my_length(list):
    print(list)
    if list:
        tmp = my_length(list[1:])+1
        print(tmp)
        return tmp
    else:
        return 0

In [364]:
my_length([1,2,3,4])

[1, 2, 3, 4]
[2, 3, 4]
[3, 4]
[4]
[]
1
2
3
4


4

In [337]:
N,T=map(int,input().split())
AB=[]
for i in range(N):
    AB.append(list(map(int,input().split())))

In [340]:
dfs=[0]*(N+1)

In [342]:
dfs

[0, 0, 0, 0]

In [343]:
def time(i,t):
    return AB[i][0]*t+AB[i][1]

In [344]:
time(1,1)

5

In [ ]:
def dfs(i,t):

    tmp=time(i,t)
    if t+tmp<=T:
        count+=1
        return 

In [289]:
N=int(input())
edge=np.zeros((N,N),int)
for i in range(N-1):
    i,j=map(int, input().split())
    edge[i-1][j-1]=1

In [290]:
edge

array([[0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [291]:
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import dijkstra

In [292]:
graph = csr_matrix(edge)

In [293]:
print(graph)

  (0, 1)	1
  (0, 2)	1
  (2, 3)	1
  (2, 4)	1


In [303]:
dist_matrix= dijkstra(csgraph=graph, directed=False)

In [304]:
position[dist_matrix==3]=1

In [305]:
for i in range(N):
    position[i][:i]=0

In [306]:
p=np.argwhere(position==1)

In [307]:
p

array([[1, 3],
       [1, 4]])

array([[1, 3],
       [1, 4],
       [3, 1],
       [4, 1]])

In [296]:
position[dist_matrix==3]=1

In [284]:
for i in range(N):
    position[i][:i]=0

In [287]:
p=position.sum(axis=0)

In [333]:
p

array([[1, 3],
       [1, 4]])

In [309]:
unique, counts = np.unique(p, return_counts=True)

In [312]:
ans=[0]*N

In [318]:
three=unique[counts.argmax()]

In [325]:
rest=[]
for i in range(N):
    rest.append(i+1)

In [326]:
ans[three]=rest.pop(2)

In [330]:
used=[]

In [331]:
used.append(3)

In [332]:
used

[3]

In [317]:
for x in p:
    if x[0]!=three and x[1]!=three:
        ans[x[0]]=
        ans[x[1]]=

array([[1, 3],
       [1, 4]])

In [334]:
counts

array([2, 1, 1])

In [244]:
A,B,M=map(int, input().split())
a=list(map(int, input().split()))
b=list(map(int, input().split()))
ans=min(a)+min(b)
for i in range(M):
    x,y,c=map(int, input().split())
    tmp=a[x-1]+b[y-1]-c
    if ans > tmp:
        ans=tmp
print(ans)

6


5

6

In [218]:
from collections import deque
S=input()
Q=int(input())
d = deque([S])
flag=0
for i in range(Q):
    x=input().split()
    if len(x)==1:
        flag=(flag+1)%2
    else:
        if int(x[1])==2:
            if flag==0:
                d.appendleft(x[2])
            else:
                d.append(x[2])
        else:
            if flag==0:
                d.append(x[2])
            else:
                d.appendleft(x[2])

        
print("ans")
if flag==1:
    print(*d, sep="")
else:
    d=list(reversed(d))
    print(*d, sep="")

ans
cpa


In [207]:
N,P=map(int,input().split())
S=input()

count=0
c_zero=1
for i in range(N):
    tmp=0
    flag=0
    for j in range(i,N):
#         print(int(S[i:j+1]),int(S[i:j+1])%P,c_zero)
        if int(S[i])==0:
            count+=c_zero
            c_zero+=1
            flag=1
            break
        else:
            if int(S[i:j+1])%P==0:
                tmp+=1
    count+=tmp*c_zero
#     print(count)
    if flag==0:
        c_zero=1
print(count)

In [214]:
count

68

In [163]:
from collections import deque
S=input()
Q=int(input())
d = deque([S])
flag=0
dic={}
dic[S]=1
for i in range(Q):
    x=input().split()
#     print(x)
    if len(x)==1:
        if len(dic.keys()) >1:
            flag=(flag+1)%2
    else:
        if len(dic.keys()) ==1:
            dic[x[2]]=1
            
        if int(x[1])==1:
            if flag==0:
                d.appendleft(x[2])
            else:
                d.append(x[2])
        else:
            if flag==0:
                d.append(x[2])
            else:
                d.appendleft(x[2])
if flag==0:
    print(*d, sep="")
else:
    d=list(reversed(d))
    print(*d, sep="")

zxy


In [126]:
from collections import deque
S=input()
Q=int(input())
d = deque([S])
flag=0
for i in range(Q):
    x=input().split()
    if len(x)==1:
        d=deque(reversed(d))
    else:
        if int(x[1])==1:
            d.appendleft(x[2])
        else:
            d.append(x[2])
print(*d, sep="")

xy


In [127]:
d

deque(['x', 'y'])

In [216]:
from collections import deque
S=input()
Q=int(input())
d = deque([S])
flag=0
for i in range(Q):
    x=input().split()
    if len(x)==1:
        flag=(flag+1)%2
    else:
        if int(x[1])==2:
            if flag==0:
                d.appendleft(x[2])
            else:
                d.append(x[2])
        else:
            if flag==0:
                d.append(x[2])
            else:
                d.appendleft(x[2])

        
print("ans")
print(flag)   
if flag==1:
    print(*d, sep="")
else:
    d=list(reversed(d))
    print(*d, sep="")

IndexError: list index out of range

In [130]:
d

deque(['x', 'y'])

xy


In [97]:
print(reversed(d), sep="")

In [51]:
query

[['2', '1', 'p'], ['1'], ['2', '2', 'c'], ['1']]

In [40]:
A_pos=list(reversed(A_pos))

In [43]:
A_pos

[4, 3]

In [44]:
A_neg

[-4, -2]

In [ ]:
i=0
j=0
s=0
while(i<n_pos-1):
    while(j<n_neg-1 and s<K):
        s

In [169]:
import numpy as np
n,k=map(int,input().split())
a=list(map(int,input().split()))
a=np.array(a)
a.sort()
nega=a[a<0]
zera=a[a==0]
posa=a[a>0]

def cnt(x):
  y=0
  if x>=0:
    y+=n*len(zera)
  y+=np.searchsorted(a,x//posa,side="right").sum()
  y+=n*len(nega)-np.searchsorted(a,-(-x//nega)).sum() 
  y-=len(a[a*a<=x])
  return y//2

r=10**18
l=-r-1
while r-l>1:
  c=(r+l)//2
  if cnt(c)>=k:
    r=c
  else:
    l=c
print(r)


-6


In [172]:
33//posa

array([11, 11])

In [167]:
cnt(10)

6

In [174]:
import numpy as np
from bisect import bisect_right as br
from bisect import bisect_left as bl
n,k=map(int,input().split())
a=np.sort(np.array(list((map(int,input().split())))))
q=len(a[a==0])
d=a[a<0]
e=a[a>0]
l,r=10**18,-10**18
while l-r>1:
    t=(l+r)//2
    p=0
    if t>=0:
        p+=q*n
    p+=np.searchsorted(a,t//e,side="right").sum()+(n-np.searchsorted(a,(-t-1)//(-d),side="right")).sum()
    p-=np.count_nonzero(a*a<=t)
    p//=2
    if p>=k:
        l=t
    else:
        r=t
    print(l)
print(l)


[2 2]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[1 1]
0
[2 2]
-4
[2 2]
-6
-6


In [145]:
n=10
S=15
a=[5,1,3,5,10,7,4,9,2,8]

In [162]:
res=n+1
s=0
t=0
summation=0

In [163]:
while(s<n-1):
    while(t<n-1 and summation<S):
        summation+=a[t]
        t+=1

    if summation < S:
#         print("now")
        break
            
    res=min(res,t-s)
#     print(s,t,t-s,summation)
    summation-=a[s]
    s+=1


    
if res > n:
    print(-1)
else:
    print(res)

2


In [1312]:
import numpy as np

# x未満のA[i]*A[j]の数
def count_pair(x):
    # A内のペアで積がxより小さいものの個数
    # まず(i,j)と(j,i)を重複して数える
    cnt = 0
    # B=x/A[i]はA[j]の候補
    # A[i]<0なる各iに対してA[j]>x/A[i]なるA[j]達の位置
    p=np.searchsorted(A, x//A_nega, side='right')
    # 上のA[j]達より大きいAの要素
    p=N-p
    # 上のA[j]達より大きいAの要素の数
    cnt += p.sum()
    if x > 0:
        # 各iに対してA[j]=0なるjの個数
        cnt += len(A_zero)*N
    # A[i]>0なる各iに対してA[j]<x/A[i]なるjの個数
    cnt += np.searchsorted(A, -(-x//A_posi), side='left').sum()
    # i=jを除いてから2で割る
    cnt = (cnt-(A**2 < x).sum())//2
    return cnt


# count_pair(x)<Kをみたすxの最大値を二分探索で求める
N, K = map(int, input().split())
* A, = map(int, input().split())
A = np.array(A)
A = np.sort(A)
A_posi = A[A > 0]
A_zero = A[A == 0]
A_nega = A[A < 0]
inf = 10**18+1
l, r = -inf, inf
# しゃくとり法
while r - l > 1:
    c = (l + r) // 2
    if count_pair(c) < K:
        l = c
    else:
        r = c
print(l)


3


In [1313]:
cnt(0)

TypeError: 'int' object is not callable

In [815]:
x=9

In [816]:
A=[1,3,3,8,9,11]
A_pos=[1,3,3,8,9,11]

In [818]:
A=np.array(A)
A_pos=np.array(A_pos)

In [819]:
np.searchsorted(A, x//A_pos, side='left')

array([4, 1, 1, 0, 0, 0])

In [825]:
(sum(np.searchsorted(A, -(-x//A_pos), side='left'))-(A**2 < x).sum())//2

3

In [827]:
(x//A_pos)

array([9, 3, 3, 1, 1, 0])

In [826]:
-(-x//A_pos)

array([9, 3, 3, 2, 1, 1])

In [808]:
count_pair(3)

39

In [257]:
count_pair(0)

154

In [245]:
x=886627544*37909651

In [246]:
x//A_nega

array([  -34574959,   -35014105,   -35415508,   -35419733,   -35843839,
         -75702278,   -78972997,   -90273088,  -125225827,  -156537118,
        -197481354,  -344394778, -1672372512, -1778666065])

In [247]:
np.searchsorted(A, x//A_nega, side='right')

array([12, 12, 12, 12, 12, 12, 12, 12, 11, 11, 10,  8,  0,  0])

In [248]:
(N-np.searchsorted(A, x//A_nega, side='right'))

array([18, 18, 18, 18, 18, 18, 18, 18, 19, 19, 20, 22, 30, 30])

In [249]:
(N-np.searchsorted(A, x//A_nega, side='right')).sum()

284

In [250]:
A_posi

array([ 21608710,  37909651, 110117526, 277222296, 398994917, 537203564,
       663621752, 798607104, 834475626, 886627544, 983211703])

In [251]:
A_nega

array([-972141167, -959948616, -949068442, -948955241, -937727165,
       -443999067, -425610555, -372334013, -268409015, -214720580,
       -170202098,  -97596546,  -20098238,  -18897162])

In [252]:
N

30

In [253]:
-(-x//A_posi)

array([1555471880,  886627544,  305235161,  121244724,   84241025,
         62567978,   50648944,   42087957,   40278877,   37909651,
         34185660])

In [254]:
np.searchsorted(A, -(-x//A_posi), side='left').sum()

248

In [255]:
# しゃくとり法xでB={A[i]*A[j]: i!=j}の中でどの位置か知る
# x<0ならi \in A_posとj \in A_negの限界を知れば良い
# x>0ならi,j \in A_posとi,j \in A_negの限界を調べて和を取れば良い
# 二分探索でxを大きくしたり小さくしたりして位置がKになるように絞り込む

In [552]:
import numpy as np
N,K=map(int,input().split())
A=list(map(int,input().split()))

In [562]:
A=[-100,-10,-1,1,10,100]

In [563]:
A=np.array(A)

In [564]:
A_pos=sorted(A[A>0])
A_neg=sorted(A[A<0])
n_pos=len(A_pos)
n_neg=len(A_neg)
# n_pos=len(A_pos)*(len(A_pos)-1)//2+len(A_neg)*(len(A_neg)-1)//2
# n_zero=len(A[A==0])*(len(A_pos)+len(A_neg))
# n_neg=len(A_pos)*len(A_neg)

In [565]:
if K<n_neg:
    print("neg")
elif n_neg<=K and K< n_neg+n_zero:
    print(0)
else:
    print("pos")
    k=K-n_neg-n_zero

0


In [566]:
A_pos=list(reversed(A_pos))

In [592]:
x=-5

In [593]:
i=0
j=0
res=N**2
prod=A_pos[i]*A_neg[j]  
while(i<n_pos-1 and prod<x):
    while(j<n_neg-1 and prod<=x):
        j+=1
        prod=A_pos[i]*A_neg[j]       
    i+=1
    prod=A_pos[i]*A_neg[j-1]

print(n_pos*n_neg-(n_pos-i)*(n_neg-j))

8


In [594]:
A_pos

[100, 10, 1]

In [595]:
A_neg

[-100, -10, -1]

In [596]:
i

2

In [597]:
j

2

In [598]:
x

-5

In [599]:
A_pos[i-1]*A_neg[j-1]

-100

In [575]:
A_pos[i]*A_neg[j]

-1000

In [576]:
A_pos[i]*A_neg[j]<x

False

In [577]:
A_pos[i-1]*A_neg[j-1]<x

False

In [578]:
A_pos[i-1]*A_neg[j]<x

False

In [579]:
A_pos[i]*A_neg[j-1]<x

True

In [580]:
n_neg

3

In [600]:
53**53

24356848165022712132477606520104725518533453128685640844505130879576720609150223301256150373