In [1]:
from ipywidgets import Textarea
import io

if 'open' in globals():
    del open
if 'input' in globals():
    del input

original_open = open

class custom_open():
    def __init__(self):
        self.text = ''

    def __call__(self, file, *args, **kwargs):
        if file == 0:
            return io.StringIO(self.text)
        return original_open(file, *args, **kwargs)

    def updater(self, change):
        self.text = change["new"]

class custom_input():
    def __init__(self):
        self.__sio = io.StringIO('')
        self.shell = get_ipython()
        if self.shell.events.callbacks['pre_run_cell'] != []:
            self.shell.events.callbacks['pre_run_cell'] = []
        self.shell.events.register('pre_run_cell', self.pre_run_cell)

    def __call__(self):
        return self.__sio.readline().strip()

    def pre_run_cell(self, info):
        text = self.shell.user_ns.get('text_area', None).value
        self.__sio = io.StringIO(text)

open = custom_open()
input = custom_input()

text_area = Textarea()
text_area.observe(open.updater, names='value')
display(text_area)

Textarea(value='')

In [198]:
N = int(input())
A = [[0 for i in range(11)] for j in range(11)]
for i in range(1, N+1):
  A[int(str(i)[0])][int(str(i)[-1])] +=1


ans = 0
for i in range(10):
  for j in range(10):
    ans += A[i][j] * A[j][i]
  
print(ans)


40812


In [201]:
A = [[0 for i in range(11)] for j in range(11)]


In [202]:
A

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [203]:
for i in range(1, N+1):
  A[int(str(i)[0])][int(str(i)[-1])] +=1

In [204]:
A

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [111, 112, 111, 111, 111, 111, 111, 111, 111, 111, 0],
 [14, 13, 14, 13, 13, 13, 13, 13, 13, 13, 0],
 [11, 11, 11, 12, 11, 11, 11, 11, 11, 11, 0],
 [11, 11, 11, 11, 12, 11, 11, 11, 11, 11, 0],
 [11, 11, 11, 11, 11, 12, 11, 11, 11, 11, 0],
 [11, 11, 11, 11, 11, 11, 12, 11, 11, 11, 0],
 [11, 11, 11, 11, 11, 11, 11, 12, 11, 11, 0],
 [11, 11, 11, 11, 11, 11, 11, 11, 12, 11, 0],
 [11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [190]:
d=[0]*100
N=int(input())
for i in range(N+1):
  s=str(i)
  d[int(s[0])*10+int(s[-1])]+=1
r=range(1,10)
print(sum(d[i*10+j]*d[j*10+i] for i in r for j in r))


40812


In [191]:
d

[1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 111,
 112,
 111,
 111,
 111,
 111,
 111,
 111,
 111,
 111,
 14,
 13,
 14,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 11,
 11,
 11,
 12,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12]

In [207]:
N=int(input())
def f(n):
    s=str(n)
    return int(s[0]),int(s[-1])

def g(x,y,N):
    ans=0
    for i in range(1,N+1):
        a,b=f(i)
        if a==x and b==y:
            ans+=1
    return ans

A=[[0 for _ in range(10)] for __ in range(10)]


for i in range(10):
    for j in range(10):
        A[i][j]=g(i,j,N)

ans=0
for i in range(10):
    for j in range(10):
        ans+=A[i][j]*A[j][i]



print(ans)

40812


In [193]:
f(1)

('1', '1')

In [154]:
N=list(input())
l=len(N)
for i in range(l):
    N[i]=int(N[i])

In [158]:
ans=108
if N[0]<=N[2]:
    ans+=4*N[0]*N[1]
else:
ans+=2*8*N[1]

In [159]:
ans

128

In [145]:
N=int(input())

In [146]:
import math
a=int(math.log10(N)+1)
b=N//(10**(a-1))
c=N%10

In [147]:
ans=0
if a<=1:
    ans=min(9,N)

In [148]:
if a<=2:
    ans=9
    if b<=c:
        ans+=3*b+(b-1)*b
    else:
        ans+=3*(b-1)+(b-2)*(b-1)+2*c

In [149]:
a,b,c

(2, 9, 9)

In [150]:
ans

108

2

In [161]:
N=int(input())

In [164]:
def f(n):
    a=int(math.log10(n)+1)
    b=n//(10**(a-1))
    c=n%10
    return b,c

In [176]:
ans=0
for i in range(1,N+1):
    a,b=f(i)
    for j in range(1,N+1):
        x,y=f(j)
        if a==y and b==x:
            ans+=1

In [177]:
ans

40812

In [181]:
def right(i,j,N):
    ans=0
    for i in range(1,N+1):
        a,b=f(i)
        for j in range(1,N+1):
            x,y=f(j)
            if a==y and b==x:
                ans+=1
    return ans

In [182]:
for i in range(2020):
    print(i,right(i))

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 9
11 12
12 12
13 12
14 12
15 12
16 12
17 12
18 12
19 12
20 12
21 14
22 17
23 17
24 17
25 17
26 17
27 17
28 17
29 17
30 17
31 19
32 21
33 24
34 24
35 24
36 24
37 24
38 24
39 24
40 24
41 26
42 28
43 30
44 33
45 33
46 33
47 33
48 33
49 33
50 33
51 35
52 37
53 39
54 41
55 44
56 44
57 44
58 44
59 44
60 44
61 46
62 48
63 50
64 52
65 54
66 57
67 57
68 57
69 57
70 57
71 59
72 61
73 63
74 65
75 67
76 69
77 72
78 72
79 72
80 72
81 74
82 76
83 78
84 80
85 82
86 84
87 86
88 89
89 89
90 89
91 91
92 93
93 95
94 97
95 99
96 101
97 103
98 105
99 108
100 108
101 113
102 115
103 117
104 119
105 121
106 123
107 125
108 127
109 129
110 129
111 136
112 138
113 140
114 142
115 144
116 146
117 148
118 150
119 152
120 152
121 161
122 163
123 165
124 167
125 169
126 171
127 173
128 175
129 177
130 177
131 188
132 190
133 192
134 194
135 196
136 198
137 200
138 202
139 204
140 204
141 217
142 219
143 221
144 223
145 225
146 227
147 229
148 231
149 233
150 233
151 248
1

KeyboardInterrupt: 

40812

In [50]:
N=int(input())
P=list(map(int, input().split()))


ans=0
p_min=P[0]
for i in range(N):
    if P[i]<=p_min:
        ans+=1
    p_min=min(p_min,P[i])
print(ans)

1


In [31]:
import numpy as np
P=np.array(P)

In [38]:
ans=0
for i in range(N):
    if P[:i+1][P[:i+1]>=P[i]].size==i+1:
        ans+=1
print(ans)

3


In [18]:
a,b=input().split()

X=""
for i in range(int(b)):
    X+=a
Y=""
for i in range(int(a)):
    Y+=b


if X>Y:
    print(Y)
else:
    print(X)

44444


In [4]:
N,M=map(int, input().split())
if N==M:
    print("Yes")
else:
    print("No")


Yes


In [15]:
N,M=map(int, input().split())
wa={}
ac=[]
key=[]
for i in range(M):
    p,s=input().split()
    if p not in ac:        
        if s=="WA":
            if s not in key:
                wa[p]=1
                key.append(p)
            else:
                wa[p]+=1
        else:
            ac.append(p)
ans=0
for i in ac:
    if i in key:
        ans+=wa[i]
print(len(ac),ans)  

2 2


In [16]:
wa

{'1': 1, '2': 1}

In [3]:
N,M=map(int, input().split())
wa={}
ac=[]
key=[]

    
for i in range(M):
    p,s=input().split()
    if p not in ac:
        if p not in key:
            key.append(p)
            wa[p]=0

        if s=="WA":
            wa[p]+=1
        else:
            ac.append(p)
ans=0
for i in key:
    if i in ac:
        ans+=wa[i]
print(len(ac),ans)



2 2


In [28]:
sx,sy =1,1
gx,gy=20,20

In [29]:
from collections import deque
import numpy as np
R,C = map(int, input().split())
# sx,sy = map(int, input().split())
# gx,gy = map(int, input().split())
maze = [list(input()) for _ in range(R)]

sx-=1
sy-=1
gx-=1
gy-=1



INF=10**5
d=[[INF for i in range(C)] for j in range(R)]

d[sx][sy]=0
que=deque(maxlen=100)
que.append([sx,sy])

dx=[0,0,1,-1]
dy=[1,-1,0,0]

while(len(que)>0):
    p=que.popleft()
    
    if p==[gx,gy]:
        break
    for i in range(4):
        x=p[0]+dx[i]
        y=p[1]+dy[i]
        
        if 0<=x and x<R and 0<=y and y<C and maze[x][y] == '.' and d[x][y] ==INF:
            d[x][y]=d[p[0]][p[1]]+1
            que.append([x,y])
            
#print(d[gx][gy])


In [30]:
d

[[0, 1, 2, 100000, 8], [1, 100000, 3, 100000, 7], [2, 100000, 4, 5, 6]]

In [43]:
dd=np.array(d)

In [44]:
np.where(dd<INF)

(array([0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2]),
 array([0, 1, 2, 4, 0, 2, 4, 0, 2, 3, 4]))

In [41]:
dd!=INF

array([[ True,  True,  True, False,  True],
       [ True, False,  True, False,  True],
       [ True, False,  True,  True,  True]])

In [9]:
from collections import deque
import numpy as np
R,C = map(int, input().split())
# sx,sy = map(int, input().split())
# gx,gy = map(int, input().split())
maze = [list(input()) for _ in range(R)]

sx-=1
sy-=1
gx-=1
gy-=1



INF=10**5
d=[[INF for i in range(C)] for j in range(R)]

d[sx][sy]=0
que=deque(maxlen=100)
que.append([sx,sy])

dx=[0,0,1,-1]
dy=[1,-1,0,0]



while(len(que)>0):
    p=que.popleft()
    
    if p==[gx,gy]:
        break
    for i in range(4):
        x=p[0]+dx[i]
        y=p[1]+dy[i]
        
        if 0<=x and x<R and 0<=y and y<C and maze[x][y] == '.' and d[x][y] ==INF:
            d[x][y]=d[p[0]][p[1]]+1
            que.append([x,y])
            
#print(d[gx][gy])



In [13]:
dd=np.array(d)

In [14]:
dd

array([[100000, 100000, 100000, 100000, 100000],
       [100000, 100000, 100000, 100000, 100000],
       [100000, 100000, 100000, 100000,      0]])

In [12]:
dd[dd!=INF]

array([0])

In [391]:
%%time
N,M=map(int, input().split())
P=[]
S=[]
for i in range(M):
    p,s=input().split()
    P.append(int(p))
    S.append(s)


import numpy as np
P=np.array(P)
S=np.array(S)

if M>0:
    ans=np.unique(P[S=="AC"])

    wa=0
    for j in ans:
        for i in S[P==j]:
            if i=="WA":
                wa+=1
            else:
                break

    print(len(ans),wa)
else:
    print(0,0)

1 0
CPU times: user 564 µs, sys: 269 µs, total: 833 µs
Wall time: 621 µs


In [49]:
N,M=map(int, input().split())
wa={}
ac=[]
key=[]

    
for i in range(M):
    p,s=input().split()
    if p not in ac:
        if p not in key:
            key.append(p)
            wa[P[i]]=0

        if s=="WA":
            wa[p]+=1
        else:
            ac.append(p)
ans=0
for i in key:
    if i in ac:
        ans+=wa[i]
print(len(ac),ans)


2 2


In [388]:
%%time
import numpy as np
N,M=map(int, input().split())
A = np.array([input().split() for i in range(M)])
P=A[:,0]
S=A[:,1]

CPU times: user 95 µs, sys: 1e+03 ns, total: 96 µs
Wall time: 100 µs


In [389]:
%%time
N,M=map(int, input().split())
P=[]
S=[]
for i in range(M):
    p,s=input().split()
    P.append(int(p))
    S.append(s)
import numpy as np
P=np.array(P)
S=np.array(S)

CPU times: user 98 µs, sys: 0 ns, total: 98 µs
Wall time: 102 µs


In [322]:
A = np.array([input().split() for i in range(M)])



In [325]:
A[:,0].astype(int)

array([1, 1, 2, 2, 2])

In [335]:
%%time

import numpy as np
N,M=map(int, input().split())
A = np.array([input().split() for i in range(M)])
if M>0:
    P=A[:,0]
    S=A[:,1]
    ans=np.unique(P[S=="AC"])

    wa=0
    for j in ans:
        for i in S[P==j]:
            if i=="WA":
                wa+=1
            else:
                break

    print(len(ans),wa)
else:
    print(0,0)

2 2
CPU times: user 418 µs, sys: 197 µs, total: 615 µs
Wall time: 482 µs


In [284]:
N,K,M=map(int, input().split())
A=list(map(int, input().split()))

ans=N*M-sum(A)
if ans>=0 and ans<=K:
    print(ans)
elif ans<0:
    print(0)
else:
    print(-1)

-1


In [285]:
ans

240

In [274]:
K

10

In [267]:
x=input()
print(chN,M=map(int, input().split())r(ord(x)+1))

z


In [262]:
print(x)

a


In [256]:
N,M=map(int, input().split())
A=list(map(int, input().split()))

import numpy as np
import fractions
A=np.array(A)

if len(A[A%2==0])!=len(A):
    ans=0
else:
    def lcm(x, y):
        return (x * y) // fractions.gcd(x, y)

    mm=1
    for x in A//2:
        mm=lcm(mm,x)

    ans=(M//mm+1)//2
print(ans)


50


/Users/masaya/.pyenv/versions/3.7.5/lib/python3.7/site-packages/ipykernel_launcher.py:12: DeprecationWarning: fractions.gcd() is deprecated. Use math.gcd() instead.
  if sys.path[0] == '':


In [258]:
N,M=map(int, input().split())
A=list(map(int, input().split()))

import numpy as np
import fractions
A=np.array(A)

def lcm(x, y):
    return (x * y) // fractions.gcd(x, y)

mm=1
for x in A//2:
    mm=lcm(mm,x)

if mm%2==0:
    ans=0
else:
    ans=int((M/mm-1)//2)+1


print(ans)


50


/Users/masaya/.pyenv/versions/3.7.5/lib/python3.7/site-packages/ipykernel_launcher.py:9: DeprecationWarning: fractions.gcd() is deprecated. Use math.gcd() instead.
  if __name__ == '__main__':


In [249]:
mm

6

In [247]:
lcm(3,1)

/Users/masaya/.pyenv/versions/3.7.5/lib/python3.7/site-packages/ipykernel_launcher.py:9: DeprecationWarning: fractions.gcd() is deprecated. Use math.gcd() instead.
  if __name__ == '__main__':


3

In [220]:
mm

45

In [213]:
mm

90

In [56]:
N=int(input())
P=list(map(int, input().split()))
Q=list(map(int, input().split()))

import itertools
import numpy as np

X=np.array(list(itertools.permutations(list(range(1,N+1)))))

pp=""
for p in P:
    pp+=str(p)
qq=""
for q in Q:
    qq+=str(q)
for i in range(len(X)):
    y=""
    for x in X[i]:
        y+=str(x)
    if y==pp:
        a=len(X)-i
    if y==qq:
        b=len(X)-i
print(abs(a-b))
        

0


In [50]:
qq

'312'

In [30]:
N=int(input())
S=input()
ans=0
c=0
for s in S:
    
    if s=="A":
        c=1
    elif s=="B" and c==1:
        c=2
    elif s=="C" and c==2:
        ans+=1
        c=0
    else:
        c=0

print(ans)

0


In [7]:
K,X=map(int, input().split())

if 500*K>=X:
    print("Yes")
else:
    print("No")

No


In [5]:
N=int(input())
X=int(input(),2)

In [6]:
X

242079196

In [4]:
def op(k):
    if k%2==0:
        return k//2 + 2**(N-1)
    else:
        return (k-1)//2

In [ ]:
import numpy as np
N=int(input())
X=int(input(),2)
def op(k):
    if k%2==0:
        return k//2 + 2**(N-1)
    else:
        return (k-1)//2
def loop(k):
    if memo[k]!=-1:
        return memo[k]
    else:
        x=op(k)
        count=1
        L=[k,x]
        while(x!=k):
            if memo[x]!=-1:
                count=0
                if x in L:
                    L.remove(x)
                break
            x=op(x)
            L.append(x)
            count+=1
        
#         print(L)
        for l in L:
            memo[l]=count
        return memo[k]
ans=0
memo=np.full(2**N,-1)
for i in range(X+1):
    ans+=loop(i)
print(ans)

In [8]:
np.full(2**N,-1)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [1]:
memo=[-1]*(2**20)

In [154]:
S=input()
K=int(input())
count=1
ans=0
old='old'
for x in S:
    if old==x:
        count+=1
    else:
        ans+=count//2
        count=1
    old=x

ans+=count//2
check1=0
check1+=ans

ans-=count//2

for x in S:
    if old==x:
        count+=1
    else:
        ans+=count//2
        count=1
#     print(count)
    old=x

ans+=count//2
check2=0
check2+=ans

ans-=count//2

for x in S:
    if old==x:
        count+=1
    else:
        ans+=count//2
        count=1
#     print(count)
    old=x

ans+=count//2

# print(check1,check2,ans)

if K==1:
    print(check1)
elif K==2:
    print(check2)
elif K==3:
    print(ans)
else:
    if (check2-check1)==(ans-check2):
        print((check2-check1)*(K-1)+check1)
    else:
        print((check2-check1)*((K-1)//2+(K-1)%2)+ (ans-check2)*((K-1)//2) +check1)


2 4 6
10


In [151]:
(K//2+K%2)

3

In [153]:
25//2

12

In [88]:
print(ans,check)

5 2


In [146]:
25//2

12

In [89]:
if ans==check*2:
    print(check*K)
if ans==check*2+1 and K!=1:
    print(check*K+1)
if ans==check*2+1 and K==1:
    print(check*K)



2


In [5]:
 def gcd(a,b):
        while b!=0:
            a,b=b,a%b
        return a

    
def make_divisors(n):
    divisors = []
    for i in range(1, int(n**0.5)+1):
        if n % i == 0:
            divisors.append(i)
            if i != n // i:
                divisors.append(n//i)

    # divisors.sort()
    return divisors

A,B=map(int, input().split())
C=max(A,B)
D=min(A,B)
lis=make_divisors(D)
lis.sort()
l=len(lis)
ans=[1]
j=1

for i in range(2,gcd(A,B)+1):
    if A % i == 0 and B % i == 0:
        j=i
        break

if j==1:
    print(1)
else:
    for i in range(l):
            if C%lis[i]==0 and pow(j,lis[i]-1,lis[i])==1:
                ans.append(lis[i])
    if C%j==0:
        ans.append(j)
    print(len(ans))


3


In [55]:
ans

[1, 2]

In [32]:
for i in range(1,math.gcd(A,B)+1):
    if A % i == 0 and B % i == 0:
        j=i
        break

In [33]:
j

1

In [6]:
def make_divisors(n):
    divisors = []
    for i in range(1, int(n**0.5)+1):
        if n % i == 0:
            divisors.append(i)
            if i != n // i:
                divisors.append(n//i)

    # divisors.sort()
    return divisors

A,B=map(int, input().split())
C=max(A,B)
lis=make_divisors(min(A,B))
lis.sort()
l=len(lis)
ans=[1]
if l>1:
    j=lis[1]
    for i in range(l):
            if C%lis[i]==0 and pow(j,lis[i]-1,lis[i])==1:
                ans.append(lis[i])
    ans.append(j)
    print(len(ans))
else:
    print(1)
    

2


In [229]:
A,B=map(int, input().split())
C=max(A,B)
lis=make_divisors(min(A,B))
lis.sort()
l=len(lis)
ans=[1]
if l>1:
    j=lis[1]
    for i in range(l):
            if C%lis[i]==0 and pow(j,lis[i]-1,lis[i])==1:
                ans.append(lis[i])
    ans.append(j)
    print(len(ans))
else:
    print(1)
    

In [230]:
lis=make_divisors(min(A,B))
lis.sort()
l=len(lis)
ans=[1]
if l>1:
    j=lis[1]
    for i in range(l):
            if C%lis[i]==0 and pow(j,lis[i]-1,lis[i])==1:
                ans.append(lis[i])
    ans.append(j)
    print(len(ans))
else:
    print(1)
    

In [231]:
ans=[1]
if l>1:
    j=lis[1]
    for i in range(l):
            if C%lis[i]==0 and pow(j,lis[i]-1,lis[i])==1:
                ans.append(lis[i])
    ans.append(j)
    print(len(ans))
else:
    print(1)
    

4


In [232]:
ans

[1, 3, 5, 2]

In [224]:
def cf(x1,x2):
    cf=[]
    for i in range(2,min(x1,x2)+1):
        if x1 % i == 0 and x2 % i == 0:
            cf.append(i)
    return cf
A,B=map(int, input().split())

ans=[]
if l>1:
    j=koyakusu[1]
    for i in range(l):
            if pow(j,koyakusu[i]-1,koyakusu[i])==1:
                ans.append(koyakusu[i])
    ans.append(j)
    print(len(ans))
else:
    print(1)

3


In [205]:
import math
math.gcd(A,B)

60

In [156]:
def cf(x1,x2):
    cf=[]
    for i in range(2,min(x1,x2)+1):
        if x1 % i == 0 and x2 % i == 0:
            cf.append(i)
            break
    return cf

In [209]:
A,B=map(int, input().split())
x=math.gcd(A,B)
for i in range(2,x+1):
    if A % i == 0 and B % i == 0:
        y=i
        break
        

In [210]:
y

2

In [207]:
A,B=map(int, input().split())
x=math.gcd(A,B)

In [208]:
x

1000000000

In [178]:
koyakusu=cf(A,B)
l=len(koyakusu)

In [179]:
koyakusu.insert(0,1)

In [180]:
koyakusu

[1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30, 60]

In [173]:
ans=[]
if l>1:
    j=koyakusu[1]
    for i in range(l):
            if pow(j,koyakusu[i]-1,koyakusu[i])==1:
                ans.append(koyakusu[i])
    ans.append(j)
    print(len(ans))
else:
    print(1)

3


In [150]:
ans

[1, 2]

In [49]:
import numpy as np
N=int(input())
A=np.array(list(map(int, input().split())))
list1=list(enumerate(A))
list2 = np.array(sorted(list1, key=lambda x:x[1]))
print(*list2[:,0]+1)

3 1 2


In [24]:
import numpy as np
N,K=map(int, input().split())
H=np.array(list(map(int, input().split())))
print(np.count_nonzero(H>=K))

5


2


In [17]:
N=int(input())
print((N//2+N%2)/N)

1.0


In [15]:
print((N//2+N%2)/N)

0.6

In [2]:
#A

In [64]:
type("No")==str

True

In [6]:
S=input()
if S=='Sunny':
    print('Cloudy')
elif S=='Cloudy':
    print('Rainy')
else:
    print('Sunny')
 

Sunny


In [7]:
#B

In [21]:
S=input()
flag=0
for i in range(len(S)):
    if i%2==0:
        if not (S[i]=='R' or S[i]=='U' or S[i]=='D'):
            flag=1
    else:
        if not (S[i]=='L' or S[i]=='U' or S[i]=='D'):
            flag=1
if flag==0:
    print('Yes')
else:
    print('No')

No


In [16]:
len(S)

7

In [22]:
#C

In [28]:
import numpy as np
N,K,Q=map(int, input().split())
A=np.array([int(input()) for _ in range(Q)])

In [35]:
P=np.array([K]*N)

In [30]:
P

array([3, 3, 3, 3, 3, 3])

In [31]:
for a in A:
    p=np.array([1]*N)
    p[a-1]=0
    P-=p

In [33]:
for x in P:
    if x>0:
        print('Yes')
    else:
        print('No')

No
No
Yes
No
No
No


In [42]:
N,K,Q=map(int, input().split())
A=[int(input()) for _ in range(Q)]
P=[0]*N
for a in A:
    P[a-1]+=1
for x in P:
    if K-Q+x>0:
        print('Yes')
    else:
        print('No')    


Yes
Yes
Yes
Yes
Yes
Yes


In [40]:
P

[2, 1, 2, 1, 3, 1, 1, 1, 3, 0]

In [43]:
#D

In [86]:
import numpy as np
N,M=map(int, input().split())
A=np.array(list(map(int, input().split())))

In [104]:
%%time
import numpy as np
N,M=map(int, input().split())
A=np.array(list(map(int, input().split())))
for i in range(M):
    x=A.argmax()
    A[x]=A[x]//2
print(sum(A))

9500000000
CPU times: user 315 µs, sys: 79 µs, total: 394 µs
Wall time: 448 µs


In [105]:
%%time
import numpy as np
N,M=map(int, input().split())
A=np.array(list(map(int, input().split())))
for i in range(M):
    x=np.argmax(A)
    A[x]=A[x]//2
print(sum(A))

9500000000
CPU times: user 538 µs, sys: 264 µs, total: 802 µs
Wall time: 632 µs


In [3]:
N,M=map(int, input().split())
A=list(map(int, input().split()))
A.index(max(A))
A.sort()
a=A.pop()
b=A.pop()
for i in range(M):
    if a>=b:
        a=a//2
    else:
        A.append(a)
        A.append(b//2)
        A.sort()
        a=A.pop()
        b=A.pop()
        
print(sum(A)+a+b)

9500000000


In [80]:
A

[1, 3, 5]

In [81]:
a

9

In [55]:
%%time
N,M=map(int, input().split())
A=list(map(int, input().split()))
A.index(max(A))
A.sort()
B=[A.pop()//2]
M-=1

while(M):
    if A[-1]>B[-1]:
        B.insert(0,A.pop()//2)
    else:
        b=B.pop()//2
        B.insert(0,b)
    M-=1
    
print(sum(A)+sum(B))


9500000000
CPU times: user 315 µs, sys: 123 µs, total: 438 µs
Wall time: 371 µs


In [52]:
A

[1]

In [53]:
B

[1, 2, 2]

In [127]:
import numpy as np
N,M=map(int, input().split())
A=np.array(list(map(int, input().split())))
while(M):
    a=A[np.argmax(A)]//2
    L=(A>=a)
    if M-len(L)>=0:
        A[L]=A[L]//2
        M-=len(L)
    else:
        x=np.argmax(A)
        A[x]=A[x]//2
        M-=1
print(sum(A))


10


In [129]:
A

array([1, 4, 3, 2])

In [125]:
len(A>=a)

4

In [126]:
1 9 3 5

SyntaxError: invalid syntax (<ipython-input-126-e330338694a4>, line 1)

In [152]:
import heapq

N,M = map(int, input().split())
A = list(-int(i) for i in input().split()) 

heapq.heapify(A)

for i in range(M):
    x=heapq.heappop(A)//(-2)
    heapq.heappush(A, -x)

print(-sum(A))


6


In [149]:
A

[-5, -4, -3, -1]

In [151]:
x

4

In [2]:
import numpy as np
H,W,A,B = map(int, input().split())

In [3]:
matrix=np.zeros([H,W], int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [56]:
import numpy as np
H,W,A,B = map(int, input().split())
def check(H,W,A,B):
    matrix=np.zeros([H,W], int)
    flag=0
    if A==0:
        flag=1
        matrix[:B,:]=1
        return matrix
    
    if B==0:
        flag=1
        matrix[:,:A]=1
        return matrix
        
    if H==W and A==B:
        flag=1
        for i in range(H//A):
            x=i*A
            matrix[x:x+A,x:x+A]=1
        return matrix
    

    if H==W and A==W//2 and B<=H//2:
        matrix[:B,:A]=1
        matrix[B:,A:]=1
        return matrix
            
    if A==W//2 and B==H//2:
        flag=1
        for i in range(H):
            for j in range(W):
                if (i+j)%2==0:
                    matrix[i][j]=1
        return matrix
    
    return "No"

if B<=H//2 and A<=W//2:
    print(check())
else:
    print("No")

[[1 1 1 0 0 0]
 [1 1 1 0 0 0]
 [1 1 1 0 0 0]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]


In [77]:
def make_divisors(n):
    divisors = []
    for i in range(1, int(n**0.5)+1):
        if n % i == 0:
            divisors.append(i)
            if i != n // i:
                divisors.append(n//i)

    # divisors.sort()
    return divisors

In [123]:
import numpy as np
H,W,A,B = map(int, input().split())
ans=np.zeros([H,W], int)
ans[:B,A:]=1
ans[B:,:A]=1
for x in ans:
    maped_num = map(str, x)
    mojiretsu = ''.join(maped_num)
    print(mojiretsu)



011111111
100000000
100000000
100000000
100000000
100000000
100000000
100000000
100000000


In [125]:
print(maped_num)

In [120]:
H, W, A, B = map(int, input().split())

for _ in range(B):
  print(''.join(['0'] * A + ['1'] * (W-A)))
for _ in range(H-B):
  print(''.join(['1'] * A + ['0'] * (W-A)))


011111111
100000000
100000000
100000000
100000000
100000000
100000000
100000000
100000000
