In [1]:
from ipywidgets import Textarea
import compe

In [2]:
open = compe.custom_open()
input = compe.custom_input()

text_area = Textarea()
text_area.observe(open.updater, names='value')
display(text_area)


Textarea(value='')

In [1]:
import static org.hamcrest.CoreMatchers.is;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import org.junit.Assert;
import org.junit.Test;

public class MainTest {

	@Test
	public void 入力例_1() throws Exception {
		String input = 
			"4 3" + System.lineSeparator() +
			"3 3 -4 -2";
		String output = 
			"-6";

		assertIO(input, output);
	}

	@Test
	public void 入力例_2() throws Exception {
		String input = 
			"10 40" + System.lineSeparator() +
			"5 4 3 2 -1 0 0 0 0 0";
		String output = 
			"6";

		assertIO(input, output);
	}

	@Test
	public void 入力例_3() throws Exception {
		String input = 
			"30 413" + System.lineSeparator() +
			"-170202098 -268409015 537203564 983211703 21608710 -443999067 -937727165 -97596546 -372334013 398994917 -972141167 798607104 -949068442 -959948616 37909651 0 886627544 -20098238 0 -948955241 0 -214720580 277222296 -18897162 834475626 0 -425610555 110117526 663621752 0";
		String output = 
			"448283280358331064";

		assertIO(input, output);
	}

	private void assertIO(String input, String output) throws Exception {
		ByteArrayInputStream in = new ByteArrayInputStream(input.getBytes());
		System.setIn(in);

		ByteArrayOutputStream out = new ByteArrayOutputStream();
		System.setOut(new PrintStream(out));

		Main.main(new String[0]);

		Assert.assertThat(out.toString(), is(output + System.lineSeparator()));
	}
}


SyntaxError: invalid syntax (<ipython-input-1-1628180bd792>, line 1)

In [7]:
import numpy as np
N,K=map(int,input().split())
A=list(map(int,input().split()))

A=np.array(A)

A_pos=np.sort(A[A>0])
A_neg=np.sort(A[A<0])
A_neg2=-A_neg[::-1]
n_pos=len(A_pos)
n_neg=len(A_neg)
n_zero=N-n_pos-n_neg

def position_in_neg(x):
    y=n_pos-np.searchsorted(A_pos,x//A_neg,side='right')
    return y.sum()

def position_in_pos(x):
    z=np.searchsorted(A_pos,-(-x//A_pos),side='left')
    w=np.searchsorted(A_neg2,-(-x//A_neg2),side='left')
    tmp=len(A_pos[A_pos**2<x])+len(A_neg2[A_neg2**2<x])
    return (z.sum()+w.sum()-tmp)//2

def position(x):
    if x<0:
        return position_in_neg(x)
    elif x==0:
        return n_pos*n_neg
    else:
        return position_in_pos(x)+n_pos*n_neg+(n_pos+n_neg)*n_zero+n_zero*(n_zero-1)//2

l=-pow(10,18)
r=pow(10,18)
while(r-l>1):
    mid=(l+r)//2
    if position(mid)<K:
        l=mid
    else:
        r=mid
print(l)

-6


In [6]:
-A_neg[::-1]

array([2, 4])

In [391]:
np.flip([1,2,3,4,5,6,7])

array([7, 6, 5, 4, 3, 2, 1])

In [2]:
    def numTest(x):
        if x.isdigit():
            return x
        else:
            return "Not a number!"

In [3]:
numTest(12313)

AttributeError: 'int' object has no attribute 'isdigit'

In [360]:
import numpy as np

# x未満のA[i]*A[j]の数
def count_pair(x):
    # A内のペアで積がxより小さいものの個数
    # まず(i,j)と(j,i)を重複して数える
    cnt = 0
    # B=x/A[i]はA[j]の候補
    # A[i]<0なる各iに対してA[j]>x/A[i]なるA[j]達の位置
    p=np.searchsorted(A, x//A_nega, side='right')
    # 上のA[j]達より大きいAの要素
    p=N-p
    # 上のA[j]達より大きいAの要素の数
    cnt += p.sum()
    if x > 0:
        # 各iに対してA[j]=0なるjの個数
        cnt += len(A_zero)*N
    # A[i]>0なる各iに対してA[j]<x/A[i]なるjの個数
    cnt += np.searchsorted(A, -(-x//A_posi), side='left').sum()
    # i=jを除いてから2で割る
    cnt = (cnt-(A**2 < x).sum())//2
    return cnt


# count_pair(x)<Kをみたすxの最大値を二分探索で求める
N, K = map(int, input().split())
* A, = map(int, input().split())
A = np.array(A)
A = np.sort(A)
A_posi = A[A > 0]
A_zero = A[A == 0]
A_nega = A[A < 0]
inf = 10**18+1
l, r = -inf, inf
# しゃくとり法
while r - l > 1:
    c = (l + r) // 2
    if count_pair(c) < K:
        l = c
    else:
        r = c
    print(l,r)
print(l)



0 1000000000000000001
0 500000000000000000
250000000000000000 500000000000000000
375000000000000000 500000000000000000
437500000000000000 500000000000000000
437500000000000000 468750000000000000
437500000000000000 453125000000000000
445312500000000000 453125000000000000
445312500000000000 449218750000000000
447265625000000000 449218750000000000
448242187500000000 449218750000000000
448242187500000000 448730468750000000
448242187500000000 448486328125000000
448242187500000000 448364257812500000
448242187500000000 448303222656250000
448272705078125000 448303222656250000
448272705078125000 448287963867187500
448280334472656250 448287963867187500
448280334472656250 448284149169921875
448282241821289062 448284149169921875
448283195495605468 448284149169921875
448283195495605468 448283672332763671
448283195495605468 448283433914184569
448283195495605468 448283314704895018
448283255100250243 448283314704895018
448283255100250243 448283284902572630
448283270001411436 448283284902572630
4482832

In [15]:


import numpy as np
N,K=map(int,input().split())
A=list(map(int,input().split()))

A=np.array(A)

A_pos=np.sort(A[A>0])
A_neg=np.sort(A[A<0])
A_neg2=np.sort(-A_neg)

np=len(A_pos)
nn=len(A_neg)
nz=N-np-nn
n_post=np*(np-1)//2+(nn*(nn-1))//2
n_zero=nz*(np+nn)+nz*(nz-1)//2
n_neg=np*nn



#array内で積がx未満になるペアの数
def syakutori_pos1(x):
    res=0
    j=np-1
    y1=-(-x//A_pos)
    for i in range(np):
        tmp=0
#         j=n-1

        while j!=-1:
            
            if A_pos[j]>=y1[i]:
                j-=1
            else:
                break
        
        tmp+=j+1
        if A_pos[i]**2<x:
            tmp-=1

        res+=tmp
    res=res//2
    return res


def syakutori_pos2(x):
    res=0
    j=nn-1
    y2=-(-x//A_neg2)
    for i in range(nn):
        tmp=0
#         j=n-1

        while j!=-1:
            
            if A_neg2[j]>=y2[i]:
                j-=1
            else:
                break
        
        tmp+=j+1
        if A_neg2[i]**2<x:
            tmp-=1

        res+=tmp
    res=res//2
    return res


#array内で積がx未満になるペアの数

def syakutori_neg(x):
    yn=x//A_neg
#     print(A_pos,y)
    res=0
    i=0
    j=np-1
    for z in reversed(yn):
        while(j!=-1):
            if z<A_pos[j]:
                j-=1
            else:
                break
#         print(z,j+1)
        res+=j+1
    return np*nn-res



def syakutori(x):
    if x>0:
        return syakutori_pos1(x)+syakutori_pos2(x)+n_neg+n_zero
    elif x==0:
        return n_neg
    else:
        return syakutori_neg(x)




r=10**18
l=-10**18
while(r-l>1):
    mid=(l+r)//2
    z=syakutori(mid)
#     z= count_pair(mid)
#     print(l,r)
    if z < K:
        l=mid
    else:
        r=mid
print(l)

-6


In [12]:
syakutori(-2)

4

In [10]:
count_pair(-10)

NameError: name 'count_pair' is not defined

In [1750]:
#array内で積がx未満になるペアの数
def syakutori_neg2(x,array_pos,array_neg):
    n_pos=len(array_pos)
    n_neg=len(array_neg)
    y=x//array_neg
#     print(A_pos,y)
    res=0
    i=0
    j=n_pos-1
    for z in reversed(y):
        while(j!=-1):
            if z<array_pos[j]:
                j-=1
            else:
                break
#         print(z,j+1)
        res+=j+1
    return n_pos*n_neg-res

In [1782]:
x=-30

In [1783]:
syakutori_neg(x,A_pos,A_neg)

0

In [1784]:
syakutori_neg2(x,A_pos,A_neg)

[3 5] [ 7 15]
15 2
7 2


0

In [1603]:
A_pos=[3,5]
A_pos=np.array(A_pos)

In [1515]:
A_neg

array([-4, -2])

In [1447]:
A_neg

array([-4, -2])

In [1231]:
if K<n_neg:
    print("neg")
    syakutori_neg()
elif n_neg<=K and K< n_neg+n_zero:
    print(0)
else:
    print("pos")
    k=K-n_neg-n_zero

pos


In [480]:
A_pos

[1, 3, 3, 8, 9, 11]

In [526]:
x=10

In [527]:
res=0
right=0
count=0
for left in range(n-1):
    while(right < len(A_pos)-1 and A_pos[left]*A_pos[right+1]<x):
        right+=1
    print(left,right, A_pos[left]*A_pos[right])
    res=max(res,right - left)
    if left<right and A_pos[left]*A_pos[right]<x:
        count+=right - left
    if left == right:
        right+=1

0 4 9
1 4 27
2 4 27
3 4 72
4 4 81
5 5 121


In [528]:
count

4

In [537]:
n,k=map(int,input().split())
arr=list(map(int,input().split()))
arr=sorted(arr)
nc=0
zc=0
pc=0
for i in range(n):
  if arr[i]<0:
    nc+=1
  elif arr[i]==0:
    zc+=1
  else:
    pc+=1
ncc=nc*pc
zcc=zc*(nc+pc)+(zc*(zc-1))//2
pcc=(nc*(nc-1))//2+(pc*(pc-1))//2
if k<=ncc:
  arr1=[]
  arr2=[]
  for i in range(n):
    if arr[i]<0:
      arr1.append(-arr[i])
    elif arr[i]>0:
      arr2.append(arr[i])
  arr1=arr1[::-1]
  c1=len(arr1)
  c2=len(arr2)
  l=0
  r=10**18+1
  k=ncc-k
  while r-l!=1:
    mid=(l+r)//2
    cnt=0
    pos=c2-1
    for i in range(c1):
      while pos!=-1:
        if arr2[pos]>mid//arr1[i]:
          pos-=1
        else:
          break        
      cnt+=pos+1
    if cnt>k:
      r=mid
    else:
      l=mid
  print(-r)
elif k<=(ncc+zcc):
  print(0)
else:
  arr1=[]
  arr2=[]
  for i in range(n):
    if arr[i]<0:
      arr1.append(-arr[i])
    elif arr[i]>0:
      arr2.append(arr[i])
  arr1=arr1[::-1]
  c1=len(arr1)
  c2=len(arr2)
  l=0
  r=10**18+1
  k-=(ncc+zcc)
  while r-l!=1:
    mid=(l+r)//2
    cnt1=0
    pos1=c1-1
    for i in range(c1):
      tmp=0
      while pos1!=-1:
        if arr1[pos1]>mid//arr1[i]:
          pos1-=1
        else:
          break
      tmp+=pos1+1
      if arr1[i]**2<mid:
        tmp-=1
      cnt1+=tmp
    cnt1=cnt1//2
    cnt2=0
    pos2=c2-1
    for i in range(c2):
      tmp=0
      while pos2!=-1:
        if arr2[pos2]>mid//arr2[i]:
          pos2-=1
        else:
          break
      tmp+=pos2+1
      if arr2[i]**2<mid:
        tmp-=1
      cnt2+=tmp
    cnt2=cnt2//2
    cnt=cnt1+cnt2
    if cnt>=k:
      r=mid
    else:
      l=mid
  print(r)


6


In [531]:
arr1=[]
arr2=[]
for i in range(n):
if arr[i]<0:
  arr1.append(-arr[i])
elif arr[i]>0:
  arr2.append(arr[i])
arr1=arr1[::-1]
c1=len(arr1)
c2=len(arr2)
l=0
r=10**18+1
k=ncc-k
while r-l!=1:
mid=(l+r)//2
cnt=0
pos=c2-1
for i in range(c1):
  while pos!=-1:
    if arr2[pos]>mid//arr1[i]:
      pos-=1
    else:
      break        
  cnt+=pos+1
if cnt>k:
  r=mid
else:
  l=mid
print(-r)

IndentationError: expected an indented block (<ipython-input-531-3642cf2a60bd>, line 4)

In [553]:
  n,k=map(int,input().split())
  arr=list(map(int,input().split()))
  arr=sorted(arr)
  nc=0
  zc=0
  pc=0
  for i in range(n):
    if arr[i]<0:
      nc+=1
    elif arr[i]==0:
      zc+=1
    else:
      pc+=1
  ncc=nc*pc
  zcc=zc*(nc+pc)+(zc*(zc-1))//2
  pcc=(nc*(nc-1))//2+(pc*(pc-1))//2
  arr1=[] # 負の数
  arr2=[] # 正の数
  for i in range(n):
    if arr[i]<0:
      arr1.append(-arr[i])
    elif arr[i]>0:
      arr2.append(arr[i])


In [554]:
arr

[-1, 0, 0, 0, 0, 0, 2, 3, 4, 5]

In [555]:
arr1

[1]

In [556]:
arr1=arr1[::-1]

In [549]:
arr2

[2, 3, 4, 5]

In [543]:
  
  c1=len(arr1)
  c2=len(arr2)
  l=0
  r=10**18+1
  k-=(ncc+zcc)
  while r-l!=1:#２分探索
    mid=(l+r)//2
    cnt1=0
    pos1=c1-1
    for i in range(c1):
      tmp=0
      while pos1!=-1:
        if arr1[pos1]>mid//arr1[i]:
          pos1-=1
        else:
          break
      tmp+=pos1+1
      if arr1[i]**2<mid:
        tmp-=1
      cnt1+=tmp
    cnt1=cnt1//2
    cnt2=0
    pos2=c2-1
    for i in range(c2):
      tmp=0
      while pos2!=-1:
        if arr2[pos2]>mid//arr2[i]:
          pos2-=1
        else:
          break
      tmp+=pos2+1
      if arr2[i]**2<mid:
        tmp-=1
      cnt2+=tmp
    cnt2=cnt2//2
    cnt=cnt1+cnt2
    if cnt>=k:
      r=mid
    else:
      l=mid
  print(r)




6


In [591]:
mid=10000

In [592]:
cnt2=0
pos2=c2-1
for i in range(c2):
    tmp=0
    while pos2!=-1:
        if arr2[pos2]>mid//arr2[i]:
            pos2-=1
        else:
            break
    tmp+=pos2+1
    if arr2[i]**2<mid:
        tmp-=1
    cnt2+=tmp
cnt2=cnt2//2



In [593]:
cnt2

6

In [1288]:
#array内で積がx未満になるペアの数
def syakutori_pos(x,array):
    n=len(array)
    res=0
    j=n-1
    for i in range(n):
        tmp=0
#         j=n-1
        y=-(-x//array[i])
        while j!=-1:
            
            if array[j]>=y:
                j-=1
            else:
                break
        
        tmp+=j+1
        if array[i]**2<x:
            tmp-=1
        res+=tmp
    res=res//2
    return res



#array内で積がx未満になるペアの数
def syakutori_neg(x,array_pos,array_neg):
    n_pos=len(array_pos)
    n_neg=len(array_neg)
    y=-(-x//array_neg)
    print(array_pos)
    print(y)
    res=0
    j=0
    k=-1
    for i in range(n_pos):
        tmp=0

        while k<n_neg-1:     
            if y[k+1]<=array_pos[i]:
                k+=1
            else:
                break
        j=max(j,k)
        while j<n_neg-1:
            if array_pos[i]<=y[j]:
                j+=1
            else:
                break
        print(k,j)
        res+=j-k
    print(res)
    return n_pos*n_neg-res

In [1289]:
syakutori_neg(-15,A_pos,A_neg)

[2 3 4 5]
[ 5 15]
-1 1
-1 1
-1 1
0 1
7


1

In [1268]:
A_pos

array([2, 3, 4, 5])

In [1269]:
A_neg

array([-3, -1])

In [461]:
n=7
K=6
a=[4,3,1,1,2,10,2]

In [462]:
res=0
right=0
mul=1
for left in range(n):
    while(right < n and mul*a[right]<=K):
        mul*=a[right]
        right+=1
    res=max(res,right - left)
    if left == right:
        right+=1
    else:


In [692]:
arr=np.array(arr)

In [693]:
import bisect

In [796]:
x=8

In [798]:
#x以下のペアの数
n=len(arr)
res=0
for i in range(n):
    b=x//arr[i]
    j=bisect.bisect_right(arr, b)
    res+=j
for j in range(n):
    if arr[j]**2<=x:
        res-=1
print(res,res//2)

6 3


In [795]:
res

10

In [802]:
x=9

In [805]:
#x未満のペアの数
n=len(arr)
res=0
for i in range(n):
    b=x//arr[i]
    j=bisect.bisect_left(arr, b)
    res+=j
    print(b,i,j,n-j)
for j in range(n):
    if arr[j]**2<x:
        res-=1
print(res,res//2)

9 0 4 2
3 1 1 5
3 2 1 5
1 3 0 6
1 4 0 6
0 5 0 6
5 2


In [361]:
def my_length(list):
    print(list)
    if list:
        tmp = my_length(list[1:])+1
        print(tmp)
        return tmp
    else:
        return 0

In [364]:
my_length([1,2,3,4])

[1, 2, 3, 4]
[2, 3, 4]
[3, 4]
[4]
[]
1
2
3
4


4

In [337]:
N,T=map(int,input().split())
AB=[]
for i in range(N):
    AB.append(list(map(int,input().split())))

In [340]:
dfs=[0]*(N+1)

In [342]:
dfs

[0, 0, 0, 0]

In [343]:
def time(i,t):
    return AB[i][0]*t+AB[i][1]

In [344]:
time(1,1)

5

In [ ]:
def dfs(i,t):

    tmp=time(i,t)
    if t+tmp<=T:
        count+=1
        return 

In [289]:
N=int(input())
edge=np.zeros((N,N),int)
for i in range(N-1):
    i,j=map(int, input().split())
    edge[i-1][j-1]=1

In [290]:
edge

array([[0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [291]:
import numpy as np
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import dijkstra

In [292]:
graph = csr_matrix(edge)

In [293]:
print(graph)

  (0, 1)	1
  (0, 2)	1
  (2, 3)	1
  (2, 4)	1


In [303]:
dist_matrix= dijkstra(csgraph=graph, directed=False)

In [304]:
position[dist_matrix==3]=1

In [305]:
for i in range(N):
    position[i][:i]=0

In [306]:
p=np.argwhere(position==1)

In [307]:
p

array([[1, 3],
       [1, 4]])

array([[1, 3],
       [1, 4],
       [3, 1],
       [4, 1]])

In [296]:
position[dist_matrix==3]=1

In [284]:
for i in range(N):
    position[i][:i]=0

In [287]:
p=position.sum(axis=0)

In [333]:
p

array([[1, 3],
       [1, 4]])

In [309]:
unique, counts = np.unique(p, return_counts=True)

In [312]:
ans=[0]*N

In [318]:
three=unique[counts.argmax()]

In [325]:
rest=[]
for i in range(N):
    rest.append(i+1)

In [326]:
ans[three]=rest.pop(2)

In [330]:
used=[]

In [331]:
used.append(3)

In [332]:
used

[3]

In [317]:
for x in p:
    if x[0]!=three and x[1]!=three:
        ans[x[0]]=
        ans[x[1]]=

array([[1, 3],
       [1, 4]])

In [334]:
counts

array([2, 1, 1])

In [244]:
A,B,M=map(int, input().split())
a=list(map(int, input().split()))
b=list(map(int, input().split()))
ans=min(a)+min(b)
for i in range(M):
    x,y,c=map(int, input().split())
    tmp=a[x-1]+b[y-1]-c
    if ans > tmp:
        ans=tmp
print(ans)

6


5

6

In [218]:
from collections import deque
S=input()
Q=int(input())
d = deque([S])
flag=0
for i in range(Q):
    x=input().split()
    if len(x)==1:
        flag=(flag+1)%2
    else:
        if int(x[1])==2:
            if flag==0:
                d.appendleft(x[2])
            else:
                d.append(x[2])
        else:
            if flag==0:
                d.append(x[2])
            else:
                d.appendleft(x[2])

        
print("ans")
if flag==1:
    print(*d, sep="")
else:
    d=list(reversed(d))
    print(*d, sep="")

ans
cpa


In [207]:
N,P=map(int,input().split())
S=input()

count=0
c_zero=1
for i in range(N):
    tmp=0
    flag=0
    for j in range(i,N):
#         print(int(S[i:j+1]),int(S[i:j+1])%P,c_zero)
        if int(S[i])==0:
            count+=c_zero
            c_zero+=1
            flag=1
            break
        else:
            if int(S[i:j+1])%P==0:
                tmp+=1
    count+=tmp*c_zero
#     print(count)
    if flag==0:
        c_zero=1
print(count)

In [214]:
count

68

In [163]:
from collections import deque
S=input()
Q=int(input())
d = deque([S])
flag=0
dic={}
dic[S]=1
for i in range(Q):
    x=input().split()
#     print(x)
    if len(x)==1:
        if len(dic.keys()) >1:
            flag=(flag+1)%2
    else:
        if len(dic.keys()) ==1:
            dic[x[2]]=1
            
        if int(x[1])==1:
            if flag==0:
                d.appendleft(x[2])
            else:
                d.append(x[2])
        else:
            if flag==0:
                d.append(x[2])
            else:
                d.appendleft(x[2])
if flag==0:
    print(*d, sep="")
else:
    d=list(reversed(d))
    print(*d, sep="")

zxy


In [126]:
from collections import deque
S=input()
Q=int(input())
d = deque([S])
flag=0
for i in range(Q):
    x=input().split()
    if len(x)==1:
        d=deque(reversed(d))
    else:
        if int(x[1])==1:
            d.appendleft(x[2])
        else:
            d.append(x[2])
print(*d, sep="")

xy


In [127]:
d

deque(['x', 'y'])

In [216]:
from collections import deque
S=input()
Q=int(input())
d = deque([S])
flag=0
for i in range(Q):
    x=input().split()
    if len(x)==1:
        flag=(flag+1)%2
    else:
        if int(x[1])==2:
            if flag==0:
                d.appendleft(x[2])
            else:
                d.append(x[2])
        else:
            if flag==0:
                d.append(x[2])
            else:
                d.appendleft(x[2])

        
print("ans")
print(flag)   
if flag==1:
    print(*d, sep="")
else:
    d=list(reversed(d))
    print(*d, sep="")

IndexError: list index out of range

In [130]:
d

deque(['x', 'y'])

xy


In [97]:
print(reversed(d), sep="")

In [51]:
query

[['2', '1', 'p'], ['1'], ['2', '2', 'c'], ['1']]

In [40]:
A_pos=list(reversed(A_pos))

In [43]:
A_pos

[4, 3]

In [44]:
A_neg

[-4, -2]

In [ ]:
i=0
j=0
s=0
while(i<n_pos-1):
    while(j<n_neg-1 and s<K):
        s

In [169]:
import numpy as np
n,k=map(int,input().split())
a=list(map(int,input().split()))
a=np.array(a)
a.sort()
nega=a[a<0]
zera=a[a==0]
posa=a[a>0]

def cnt(x):
  y=0
  if x>=0:
    y+=n*len(zera)
  y+=np.searchsorted(a,x//posa,side="right").sum()
  y+=n*len(nega)-np.searchsorted(a,-(-x//nega)).sum() 
  y-=len(a[a*a<=x])
  return y//2

r=10**18
l=-r-1
while r-l>1:
  c=(r+l)//2
  if cnt(c)>=k:
    r=c
  else:
    l=c
print(r)


-6


In [172]:
33//posa

array([11, 11])

In [167]:
cnt(10)

6

In [174]:
import numpy as np
from bisect import bisect_right as br
from bisect import bisect_left as bl
n,k=map(int,input().split())
a=np.sort(np.array(list((map(int,input().split())))))
q=len(a[a==0])
d=a[a<0]
e=a[a>0]
l,r=10**18,-10**18
while l-r>1:
    t=(l+r)//2
    p=0
    if t>=0:
        p+=q*n
    p+=np.searchsorted(a,t//e,side="right").sum()+(n-np.searchsorted(a,(-t-1)//(-d),side="right")).sum()
    p-=np.count_nonzero(a*a<=t)
    p//=2
    if p>=k:
        l=t
    else:
        r=t
    print(l)
print(l)


[2 2]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[0 0]
0
[1 1]
0
[2 2]
-4
[2 2]
-6
-6


In [145]:
n=10
S=15
a=[5,1,3,5,10,7,4,9,2,8]

In [162]:
res=n+1
s=0
t=0
summation=0

In [163]:
while(s<n-1):
    while(t<n-1 and summation<S):
        summation+=a[t]
        t+=1

    if summation < S:
#         print("now")
        break
            
    res=min(res,t-s)
#     print(s,t,t-s,summation)
    summation-=a[s]
    s+=1


    
if res > n:
    print(-1)
else:
    print(res)

2


In [1312]:
import numpy as np

# x未満のA[i]*A[j]の数
def count_pair(x):
    # A内のペアで積がxより小さいものの個数
    # まず(i,j)と(j,i)を重複して数える
    cnt = 0
    # B=x/A[i]はA[j]の候補
    # A[i]<0なる各iに対してA[j]>x/A[i]なるA[j]達の位置
    p=np.searchsorted(A, x//A_nega, side='right')
    # 上のA[j]達より大きいAの要素
    p=N-p
    # 上のA[j]達より大きいAの要素の数
    cnt += p.sum()
    if x > 0:
        # 各iに対してA[j]=0なるjの個数
        cnt += len(A_zero)*N
    # A[i]>0なる各iに対してA[j]<x/A[i]なるjの個数
    cnt += np.searchsorted(A, -(-x//A_posi), side='left').sum()
    # i=jを除いてから2で割る
    cnt = (cnt-(A**2 < x).sum())//2
    return cnt


# count_pair(x)<Kをみたすxの最大値を二分探索で求める
N, K = map(int, input().split())
* A, = map(int, input().split())
A = np.array(A)
A = np.sort(A)
A_posi = A[A > 0]
A_zero = A[A == 0]
A_nega = A[A < 0]
inf = 10**18+1
l, r = -inf, inf
# しゃくとり法
while r - l > 1:
    c = (l + r) // 2
    if count_pair(c) < K:
        l = c
    else:
        r = c
print(l)


3


In [1313]:
cnt(0)

TypeError: 'int' object is not callable

In [815]:
x=9

In [816]:
A=[1,3,3,8,9,11]
A_pos=[1,3,3,8,9,11]

In [818]:
A=np.array(A)
A_pos=np.array(A_pos)

In [819]:
np.searchsorted(A, x//A_pos, side='left')

array([4, 1, 1, 0, 0, 0])

In [825]:
(sum(np.searchsorted(A, -(-x//A_pos), side='left'))-(A**2 < x).sum())//2

3

In [827]:
(x//A_pos)

array([9, 3, 3, 1, 1, 0])

In [826]:
-(-x//A_pos)

array([9, 3, 3, 2, 1, 1])

In [808]:
count_pair(3)

39

In [257]:
count_pair(0)

154

In [245]:
x=886627544*37909651

In [246]:
x//A_nega

array([  -34574959,   -35014105,   -35415508,   -35419733,   -35843839,
         -75702278,   -78972997,   -90273088,  -125225827,  -156537118,
        -197481354,  -344394778, -1672372512, -1778666065])

In [247]:
np.searchsorted(A, x//A_nega, side='right')

array([12, 12, 12, 12, 12, 12, 12, 12, 11, 11, 10,  8,  0,  0])

In [248]:
(N-np.searchsorted(A, x//A_nega, side='right'))

array([18, 18, 18, 18, 18, 18, 18, 18, 19, 19, 20, 22, 30, 30])

In [249]:
(N-np.searchsorted(A, x//A_nega, side='right')).sum()

284

In [250]:
A_posi

array([ 21608710,  37909651, 110117526, 277222296, 398994917, 537203564,
       663621752, 798607104, 834475626, 886627544, 983211703])

In [251]:
A_nega

array([-972141167, -959948616, -949068442, -948955241, -937727165,
       -443999067, -425610555, -372334013, -268409015, -214720580,
       -170202098,  -97596546,  -20098238,  -18897162])

In [252]:
N

30

In [253]:
-(-x//A_posi)

array([1555471880,  886627544,  305235161,  121244724,   84241025,
         62567978,   50648944,   42087957,   40278877,   37909651,
         34185660])

In [254]:
np.searchsorted(A, -(-x//A_posi), side='left').sum()

248

In [255]:
# しゃくとり法xでB={A[i]*A[j]: i!=j}の中でどの位置か知る
# x<0ならi \in A_posとj \in A_negの限界を知れば良い
# x>0ならi,j \in A_posとi,j \in A_negの限界を調べて和を取れば良い
# 二分探索でxを大きくしたり小さくしたりして位置がKになるように絞り込む

In [552]:
import numpy as np
N,K=map(int,input().split())
A=list(map(int,input().split()))

In [562]:
A=[-100,-10,-1,1,10,100]

In [563]:
A=np.array(A)

In [564]:
A_pos=sorted(A[A>0])
A_neg=sorted(A[A<0])
n_pos=len(A_pos)
n_neg=len(A_neg)
# n_pos=len(A_pos)*(len(A_pos)-1)//2+len(A_neg)*(len(A_neg)-1)//2
# n_zero=len(A[A==0])*(len(A_pos)+len(A_neg))
# n_neg=len(A_pos)*len(A_neg)

In [565]:
if K<n_neg:
    print("neg")
elif n_neg<=K and K< n_neg+n_zero:
    print(0)
else:
    print("pos")
    k=K-n_neg-n_zero

0


In [566]:
A_pos=list(reversed(A_pos))

In [592]:
x=-5

In [593]:
i=0
j=0
res=N**2
prod=A_pos[i]*A_neg[j]  
while(i<n_pos-1 and prod<x):
    while(j<n_neg-1 and prod<=x):
        j+=1
        prod=A_pos[i]*A_neg[j]       
    i+=1
    prod=A_pos[i]*A_neg[j-1]

print(n_pos*n_neg-(n_pos-i)*(n_neg-j))

8


In [594]:
A_pos

[100, 10, 1]

In [595]:
A_neg

[-100, -10, -1]

In [596]:
i

2

In [597]:
j

2

In [598]:
x

-5

In [599]:
A_pos[i-1]*A_neg[j-1]

-100

In [575]:
A_pos[i]*A_neg[j]

-1000

In [576]:
A_pos[i]*A_neg[j]<x

False

In [577]:
A_pos[i-1]*A_neg[j-1]<x

False

In [578]:
A_pos[i-1]*A_neg[j]<x

False

In [579]:
A_pos[i]*A_neg[j-1]<x

True

In [580]:
n_neg

3

In [600]:
53**53

24356848165022712132477606520104725518533453128685640844505130879576720609150223301256150373