In [10]:
from ipywidgets import Textarea
import io

if 'open' in globals():
    del open
if 'input' in globals():
    del input

original_open = open

class custom_open():
    def __init__(self):
        self.text = ''

    def __call__(self, file, *args, **kwargs):
        if file == 0:
            return io.StringIO(self.text)
        return original_open(file, *args, **kwargs)

    def updater(self, change):
        self.text = change["new"]

class custom_input():
    def __init__(self):
        self.__sio = io.StringIO('')
        self.shell = get_ipython()
        if self.shell.events.callbacks['pre_run_cell'] != []:
            self.shell.events.callbacks['pre_run_cell'] = []
        self.shell.events.register('pre_run_cell', self.pre_run_cell)

    def __call__(self):
        return self.__sio.readline().strip()

    def pre_run_cell(self, info):
        text = self.shell.user_ns.get('text_area', None).value
        self.__sio = io.StringIO(text)

open = custom_open()
input = custom_input()

text_area = Textarea()
text_area.observe(open.updater, names='value')
display(text_area)

Textarea(value='')

In [5]:
N=int(input())
X=int(input(),2)

In [6]:
X

242079196

In [4]:
def op(k):
    if k%2==0:
        return k//2 + 2**(N-1)
    else:
        return (k-1)//2

In [ ]:
import numpy as np
N=int(input())
X=int(input(),2)
def op(k):
    if k%2==0:
        return k//2 + 2**(N-1)
    else:
        return (k-1)//2
def loop(k):
    if memo[k]!=-1:
        return memo[k]
    else:
        x=op(k)
        count=1
        L=[k,x]
        while(x!=k):
            if memo[x]!=-1:
                count=0
                if x in L:
                    L.remove(x)
                break
            x=op(x)
            L.append(x)
            count+=1
        
#         print(L)
        for l in L:
            memo[l]=count
        return memo[k]
ans=0
memo=np.full(2**N,-1)
for i in range(X+1):
    ans+=loop(i)
print(ans)

In [8]:
np.full(2**N,-1)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [1]:
memo=[-1]*(2**20)

In [154]:
S=input()
K=int(input())
count=1
ans=0
old='old'
for x in S:
    if old==x:
        count+=1
    else:
        ans+=count//2
        count=1
    old=x

ans+=count//2
check1=0
check1+=ans

ans-=count//2

for x in S:
    if old==x:
        count+=1
    else:
        ans+=count//2
        count=1
#     print(count)
    old=x

ans+=count//2
check2=0
check2+=ans

ans-=count//2

for x in S:
    if old==x:
        count+=1
    else:
        ans+=count//2
        count=1
#     print(count)
    old=x

ans+=count//2

# print(check1,check2,ans)

if K==1:
    print(check1)
elif K==2:
    print(check2)
elif K==3:
    print(ans)
else:
    if (check2-check1)==(ans-check2):
        print((check2-check1)*(K-1)+check1)
    else:
        print((check2-check1)*((K-1)//2+(K-1)%2)+ (ans-check2)*((K-1)//2) +check1)


2 4 6
10


In [151]:
(K//2+K%2)

3

In [153]:
25//2

12

In [88]:
print(ans,check)

5 2


In [146]:
25//2

12

In [89]:
if ans==check*2:
    print(check*K)
if ans==check*2+1 and K!=1:
    print(check*K+1)
if ans==check*2+1 and K==1:
    print(check*K)



2


In [5]:
 def gcd(a,b):
        while b!=0:
            a,b=b,a%b
        return a

    
def make_divisors(n):
    divisors = []
    for i in range(1, int(n**0.5)+1):
        if n % i == 0:
            divisors.append(i)
            if i != n // i:
                divisors.append(n//i)

    # divisors.sort()
    return divisors

A,B=map(int, input().split())
C=max(A,B)
D=min(A,B)
lis=make_divisors(D)
lis.sort()
l=len(lis)
ans=[1]
j=1

for i in range(2,gcd(A,B)+1):
    if A % i == 0 and B % i == 0:
        j=i
        break

if j==1:
    print(1)
else:
    for i in range(l):
            if C%lis[i]==0 and pow(j,lis[i]-1,lis[i])==1:
                ans.append(lis[i])
    if C%j==0:
        ans.append(j)
    print(len(ans))


3


In [55]:
ans

[1, 2]

In [32]:
for i in range(1,math.gcd(A,B)+1):
    if A % i == 0 and B % i == 0:
        j=i
        break

In [33]:
j

1

In [6]:
def make_divisors(n):
    divisors = []
    for i in range(1, int(n**0.5)+1):
        if n % i == 0:
            divisors.append(i)
            if i != n // i:
                divisors.append(n//i)

    # divisors.sort()
    return divisors

A,B=map(int, input().split())
C=max(A,B)
lis=make_divisors(min(A,B))
lis.sort()
l=len(lis)
ans=[1]
if l>1:
    j=lis[1]
    for i in range(l):
            if C%lis[i]==0 and pow(j,lis[i]-1,lis[i])==1:
                ans.append(lis[i])
    ans.append(j)
    print(len(ans))
else:
    print(1)
    

2


In [229]:
A,B=map(int, input().split())
C=max(A,B)
lis=make_divisors(min(A,B))
lis.sort()
l=len(lis)
ans=[1]
if l>1:
    j=lis[1]
    for i in range(l):
            if C%lis[i]==0 and pow(j,lis[i]-1,lis[i])==1:
                ans.append(lis[i])
    ans.append(j)
    print(len(ans))
else:
    print(1)
    

In [230]:
lis=make_divisors(min(A,B))
lis.sort()
l=len(lis)
ans=[1]
if l>1:
    j=lis[1]
    for i in range(l):
            if C%lis[i]==0 and pow(j,lis[i]-1,lis[i])==1:
                ans.append(lis[i])
    ans.append(j)
    print(len(ans))
else:
    print(1)
    

In [231]:
ans=[1]
if l>1:
    j=lis[1]
    for i in range(l):
            if C%lis[i]==0 and pow(j,lis[i]-1,lis[i])==1:
                ans.append(lis[i])
    ans.append(j)
    print(len(ans))
else:
    print(1)
    

4


In [232]:
ans

[1, 3, 5, 2]

In [224]:
def cf(x1,x2):
    cf=[]
    for i in range(2,min(x1,x2)+1):
        if x1 % i == 0 and x2 % i == 0:
            cf.append(i)
    return cf
A,B=map(int, input().split())

ans=[]
if l>1:
    j=koyakusu[1]
    for i in range(l):
            if pow(j,koyakusu[i]-1,koyakusu[i])==1:
                ans.append(koyakusu[i])
    ans.append(j)
    print(len(ans))
else:
    print(1)

3


In [205]:
import math
math.gcd(A,B)

60

In [156]:
def cf(x1,x2):
    cf=[]
    for i in range(2,min(x1,x2)+1):
        if x1 % i == 0 and x2 % i == 0:
            cf.append(i)
            break
    return cf

In [209]:
A,B=map(int, input().split())
x=math.gcd(A,B)
for i in range(2,x+1):
    if A % i == 0 and B % i == 0:
        y=i
        break
        

In [210]:
y

2

In [207]:
A,B=map(int, input().split())
x=math.gcd(A,B)

In [208]:
x

1000000000

In [178]:
koyakusu=cf(A,B)
l=len(koyakusu)

In [179]:
koyakusu.insert(0,1)

In [180]:
koyakusu

[1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30, 60]

In [173]:
ans=[]
if l>1:
    j=koyakusu[1]
    for i in range(l):
            if pow(j,koyakusu[i]-1,koyakusu[i])==1:
                ans.append(koyakusu[i])
    ans.append(j)
    print(len(ans))
else:
    print(1)

3


In [150]:
ans

[1, 2]

In [49]:
import numpy as np
N=int(input())
A=np.array(list(map(int, input().split())))
list1=list(enumerate(A))
list2 = np.array(sorted(list1, key=lambda x:x[1]))
print(*list2[:,0]+1)

3 1 2


In [24]:
import numpy as np
N,K=map(int, input().split())
H=np.array(list(map(int, input().split())))
print(np.count_nonzero(H>=K))

5


2


In [17]:
N=int(input())
print((N//2+N%2)/N)

1.0


In [15]:
print((N//2+N%2)/N)

0.6

In [2]:
#A

In [64]:
type("No")==str

True

In [6]:
S=input()
if S=='Sunny':
    print('Cloudy')
elif S=='Cloudy':
    print('Rainy')
else:
    print('Sunny')
 

Sunny


In [7]:
#B

In [21]:
S=input()
flag=0
for i in range(len(S)):
    if i%2==0:
        if not (S[i]=='R' or S[i]=='U' or S[i]=='D'):
            flag=1
    else:
        if not (S[i]=='L' or S[i]=='U' or S[i]=='D'):
            flag=1
if flag==0:
    print('Yes')
else:
    print('No')

No


In [16]:
len(S)

7

In [22]:
#C

In [28]:
import numpy as np
N,K,Q=map(int, input().split())
A=np.array([int(input()) for _ in range(Q)])

In [35]:
P=np.array([K]*N)

In [30]:
P

array([3, 3, 3, 3, 3, 3])

In [31]:
for a in A:
    p=np.array([1]*N)
    p[a-1]=0
    P-=p

In [33]:
for x in P:
    if x>0:
        print('Yes')
    else:
        print('No')

No
No
Yes
No
No
No


In [42]:
N,K,Q=map(int, input().split())
A=[int(input()) for _ in range(Q)]
P=[0]*N
for a in A:
    P[a-1]+=1
for x in P:
    if K-Q+x>0:
        print('Yes')
    else:
        print('No')    


Yes
Yes
Yes
Yes
Yes
Yes


In [40]:
P

[2, 1, 2, 1, 3, 1, 1, 1, 3, 0]

In [43]:
#D

In [86]:
import numpy as np
N,M=map(int, input().split())
A=np.array(list(map(int, input().split())))

In [104]:
%%time
import numpy as np
N,M=map(int, input().split())
A=np.array(list(map(int, input().split())))
for i in range(M):
    x=A.argmax()
    A[x]=A[x]//2
print(sum(A))

9500000000
CPU times: user 315 µs, sys: 79 µs, total: 394 µs
Wall time: 448 µs


In [105]:
%%time
import numpy as np
N,M=map(int, input().split())
A=np.array(list(map(int, input().split())))
for i in range(M):
    x=np.argmax(A)
    A[x]=A[x]//2
print(sum(A))

9500000000
CPU times: user 538 µs, sys: 264 µs, total: 802 µs
Wall time: 632 µs


In [3]:
N,M=map(int, input().split())
A=list(map(int, input().split()))
A.index(max(A))
A.sort()
a=A.pop()
b=A.pop()
for i in range(M):
    if a>=b:
        a=a//2
    else:
        A.append(a)
        A.append(b//2)
        A.sort()
        a=A.pop()
        b=A.pop()
        
print(sum(A)+a+b)

9500000000


In [80]:
A

[1, 3, 5]

In [81]:
a

9

In [55]:
%%time
N,M=map(int, input().split())
A=list(map(int, input().split()))
A.index(max(A))
A.sort()
B=[A.pop()//2]
M-=1

while(M):
    if A[-1]>B[-1]:
        B.insert(0,A.pop()//2)
    else:
        b=B.pop()//2
        B.insert(0,b)
    M-=1
    
print(sum(A)+sum(B))


9500000000
CPU times: user 315 µs, sys: 123 µs, total: 438 µs
Wall time: 371 µs


In [52]:
A

[1]

In [53]:
B

[1, 2, 2]

In [127]:
import numpy as np
N,M=map(int, input().split())
A=np.array(list(map(int, input().split())))
while(M):
    a=A[np.argmax(A)]//2
    L=(A>=a)
    if M-len(L)>=0:
        A[L]=A[L]//2
        M-=len(L)
    else:
        x=np.argmax(A)
        A[x]=A[x]//2
        M-=1
print(sum(A))


10


In [129]:
A

array([1, 4, 3, 2])

In [125]:
len(A>=a)

4

In [126]:
1 9 3 5

SyntaxError: invalid syntax (<ipython-input-126-e330338694a4>, line 1)

In [152]:
import heapq

N,M = map(int, input().split())
A = list(-int(i) for i in input().split()) 

heapq.heapify(A)

for i in range(M):
    x=heapq.heappop(A)//(-2)
    heapq.heappush(A, -x)

print(-sum(A))


6


In [149]:
A

[-5, -4, -3, -1]

In [151]:
x

4

In [2]:
import numpy as np
H,W,A,B = map(int, input().split())

In [3]:
matrix=np.zeros([H,W], int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [56]:
import numpy as np
H,W,A,B = map(int, input().split())
def check(H,W,A,B):
    matrix=np.zeros([H,W], int)
    flag=0
    if A==0:
        flag=1
        matrix[:B,:]=1
        return matrix
    
    if B==0:
        flag=1
        matrix[:,:A]=1
        return matrix
        
    if H==W and A==B:
        flag=1
        for i in range(H//A):
            x=i*A
            matrix[x:x+A,x:x+A]=1
        return matrix
    

    if H==W and A==W//2 and B<=H//2:
        matrix[:B,:A]=1
        matrix[B:,A:]=1
        return matrix
            
    if A==W//2 and B==H//2:
        flag=1
        for i in range(H):
            for j in range(W):
                if (i+j)%2==0:
                    matrix[i][j]=1
        return matrix
    
    return "No"

if B<=H//2 and A<=W//2:
    print(check())
else:
    print("No")

[[1 1 1 0 0 0]
 [1 1 1 0 0 0]
 [1 1 1 0 0 0]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]


In [77]:
def make_divisors(n):
    divisors = []
    for i in range(1, int(n**0.5)+1):
        if n % i == 0:
            divisors.append(i)
            if i != n // i:
                divisors.append(n//i)

    # divisors.sort()
    return divisors

In [123]:
import numpy as np
H,W,A,B = map(int, input().split())
ans=np.zeros([H,W], int)
ans[:B,A:]=1
ans[B:,:A]=1
for x in ans:
    maped_num = map(str, x)
    mojiretsu = ''.join(maped_num)
    print(mojiretsu)



011111111
100000000
100000000
100000000
100000000
100000000
100000000
100000000
100000000


In [125]:
print(maped_num)

In [120]:
H, W, A, B = map(int, input().split())

for _ in range(B):
  print(''.join(['0'] * A + ['1'] * (W-A)))
for _ in range(H-B):
  print(''.join(['1'] * A + ['0'] * (W-A)))


011111111
100000000
100000000
100000000
100000000
100000000
100000000
100000000
100000000
